# Projeto para departamento de Recursos Humanos - Triagem e Análise de currículos

O objetivo com esse estudo de caso é classificar currículos automaticamente com base nos requisitos da vaga, destacando candidatos mais aderentes, além de sugerir perguntas de entrevista personalizadas.

A ideia é carregar currículos (em PDF ou texto), processar cada um com um prompt bem definido e extrair dados estruturados (como nome, área, nível, competências etc.) em formato utilizável (como JSON ou CSV).

## Instalação das bibliotecas

In [ ]:
!pip install langchain-groq langchain-community langchain-core PyMuPDF -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 30.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.5/137.5 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 25.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 3.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

## Carregando os documentos

Antes de começarmos, envie o documento PDF ao Colab. Você pode arrastar o arquivo no painel lateral (dentro da aba 'Arquivos') ou usar o código abaixo

In [ ]:
from google.colab import files
uploaded = files.upload()
file_path = list(uploaded.keys())[0]
print(f"Arquivo carregado: {file_path}")

Saving Currículo1.pdf to Currículo1.pdf
Saving Currículo2.pdf to Currículo2.pdf
Saving Currículo3.pdf to Currículo3.pdf
Arquivo carregado: Currículo1.pdf

## Extração de conteúdos

In [12]:
import os
import fitz # PyMuPDF

path = "/content/Currículo3.pdf"

def extract_text_pdf(filepath):
  doc = fitz.open(filepath)
  text = ""
  for page in doc:
    text += page.get_text()
  doc.close()
  return text.strip()

In [13]:
extract_text_pdf(path)

'Alex Costa\u200b\nE-mail: alex@creativeflow.com.br    LinkedIn: linkedin.com/in/alex-costa \n \nMEU OBJETIVO \nProfissional multidisciplinar com 5 anos de experiência integrando design, \ndesenvolvimento front-end e estratégias de marketing digital. Busco aprimorar \nhabilidades em design de interfaces complexas e explorar soluções criativas que \nunam estética, usabilidade e performance técnica. \n \nMINHA FORMAÇÃO ACADÊMICA \nBacharelado em Design Digital\u200b\nUniversidade Federal do Paraná (UFPR) – Curitiba, PR\u200b\nMar 2016 – Dez 2020 \n●\u200b Bolsista do programa de inovação em interfaces responsivas. \n●\u200b TCC: "Design Systems para Aplicações Escaláveis: Unindo Figma e React". \nCurso Técnico em Marketing Digital\u200b\nInstituto de Tecnologia e Design (ITEDE)\u200b\nJan 2014 – Dez 2015 \n \nMINHA EXPERIÊNCIA PROFISSIONAL \nUI/UX Designer & Front-End Developer | DigitalMind Creative Studio\u200b\nJul 2021 – Atual \n●\u200b Criação de interfaces para 12+ produtos web e mobile, usando Figma e \nimplementação com React.js e Vue.js. \n●\u200b Colaboração com equipes de marketing na construção de landing pages \nhigh-conversion (aumento de 35% em taxas de engajamento). \n●\u200b Desenvolvimento de componentes reutilizáveis em Storybook para acelerar \nworkflows de design e desenvolvimento. \nDesigner de Produto e Marketing | Agência Pulse\u200b\nJan 2019 – Jun 2021 \n●\u200b Liderança de projetos de branding para clientes de e-commerce, incluindo \nidentidade visual e campanhas de mídia social. \n●\u200b Integração de ferramentas de análise (Google Analytics, Hotjar) em websites \npara otimização de UX. \n●\u200b Automação de fluxos de marketing com WordPress e plugins personalizados \nem PHP. \nFreelancer em Design e Desenvolvimento Web\u200b\nAgo 2017 – Dez 2018 \n●\u200b Design e codificação de sites para startups, com foco em mobile-first e SEO. \n●\u200b Criação de conteúdo visual para redes sociais (Adobe Creative Suite) e \nintegração com CMS como Shopify e Webflow. \n \nHABILIDADES TÉCNICAS \n●\u200b Design: Figma, Adobe XD, Photoshop, Illustrator, Prototipagem Interativa \n●\u200b Front-End: HTML/CSS, JavaScript (ES6+), React.js, Vue.js, SASS \n●\u200b Back-End Leve: Node.js (Express para APIs simples), Firebase (Firestore, \nAuth) \n●\u200b Marketing: Google Analytics, SEO, WordPress, Shopify, Mailchimp \n●\u200b Ferramentas: Git, Webpack, Jira, Zeplin, A/B Testing \n \nCERTIFICAÇÕES \n●\u200b Adobe Certified Expert (ACE) em UX Design (2022) \n●\u200b Certificação Professional em JavaScript (Codecademy Pro, 2021) \n●\u200b Google Analytics Individual Qualification (2020) \n \nIDIOMAS \n●\u200b Português: Nativo \n●\u200b Inglês: Fluente (TOEIC: 950/990) \n●\u200b Espanhol: Intermediário \n \nPROJETOS DESTACADOS \nSistema de Design para Plataforma de Educação \n●\u200b Criação de design system modular (Figma + React) adotado por 20+ times \ninternos. \n●\u200b Redução de 40% no tempo de desenvolvimento de novas features. \nE-commerce Sustentável "EcoStyle" \n●\u200b Design de interface e desenvolvimento front-end (Vue.js + Shopify). \n●\u200b Estratégia de marketing integrada: aumento de 50% em tráfego orgânico em 6 \nmeses. \n \nINFORMAÇÕES ADICIONAIS \n●\u200b Voluntariado: Mentoria em design para jovens em comunidades tech (Projeto \nDesign para Todos). \n●\u200b Prêmios: 2º lugar no Prêmio Nacional de Design Digital (2021) com projeto de \nacessibilidade web. \n●\u200b Interesses: Design sustentável, motion graphics, participação em meetups de \nfront-end.'

## Parsing de documentos com Docling

In [14]:
!pip install -q docling

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 675.7/675.7 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 282.1/282.1 kB 18.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.0/94.0 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 46.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.0/43.0 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 102.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 18.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.8/472.8 kB 29.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.3/27.3 MB 47.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.0/56.0 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 79.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 978.2/978.2 kB 53.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 667.5/667.5 kB 41.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.3/94.3 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.7/99.7 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.1/108.1 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.0/345.0 kB 24.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 272.8/272.8 kB 20.9 MB/s eta 0:00:00
  Building wheel for pylatexenc (setup.py) ... done

In [15]:
from docling.document_converter import DocumentConverter

converter = DocumentConverter()
result = converter.convert(path)
print(result.document.export_to_markdown())

[INFO] 2026-07-20 19:30:01,237 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 19:30:01,243 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 19:30:01,248 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.9.1/torch/PP-OCRv4/det/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 19:30:02,663 [RapidOCR] download_file.py:82: Download size: 13.83MB
[INFO] 2026-07-20 19:30:02,943 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 19:30:02,946 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 19:30:03,261 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 19:30:03,263 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 19:30:03,265 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.9.1/torch/PP-OCRv4/cls/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 19:30:04,061 [RapidOCR] download_file.py:82: Download size: 0.56MB
[INFO] 2026-07-20 19:30:04,087 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 19:30:04,090 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 19:30:04,210 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 19:30:04,211 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 19:30:04,213 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.9.1/torch/PP-OCRv4/rec/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-07-20 19:30:05,100 [RapidOCR] download_file.py:82: Download size: 25.67MB
[INFO] 2026-07-20 19:30:05,634 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-07-20 19:30:05,637 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-07-20 19:30:06,296 [RapidOCR] download_file.py:68: Initiating download: https://www.modelscope.cn/models/RapidAI/RapidOCR/resolve/v3.9.1/paddle/PP-OCRv4/rec/ch_PP-OCRv4_rec_mobile/ppocr_keys_v1.txt
[INFO] 2026-07-20 19:30:07,007 [RapidOCR] download_file.py:82: Download size: 0.03MB
[INFO] 2026-07-20 19:30:07,190 [RapidOCR] download_file.py:95: Successfully saved to: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ppocr_keys_v1.txt
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

## Alex Costa

E-mail: alex@creativeflow.com.br LinkedIn: linkedin.com/in/alex-costa

## MEU OBJETIVO

Profissional multidisciplinar com 5 anos de experiência integrando design, desenvolvimento front-end e estratégias de marketing digital. Busco aprimorar habilidades em design de interfaces complexas e explorar soluções criativas que unam estética, usabilidade e performance técnica.

## MINHA FORMAÇÃO ACADÊMICA

## Bacharelado em Design Digital

Universidade Federal do Paraná (UFPR) - Curitiba, PR

Mar 2016 - Dez 2020

- Bolsista do programa de inovação em interfaces responsivas.
- TCC: "Design Systems para Aplicações Escaláveis: Unindo Figma e React".

## Curso Técnico em Marketing Digital

Instituto de Tecnologia e Design (ITEDE) Jan 2014 - Dez 2015

## MINHA EXPERIÊNCIA PROFISSIONAL

## UI/UX Designer &amp; Front-End Developer | DigitalMind Creative Studio

Jul 2021 - Atual

- Criação de interfaces para 12+ produtos web e mobile, usando Figma e implementação com React.js e Vue.js .
- Colaboração com equipes de marketing na construção de landing pages high-conversion (aumento de 35% em taxas de engajamento).
- Desenvolvimento de componentes reutilizáveis em Storybook para acelerar workflows de design e desenvolvimento.

## Designer de Produto e Marketing | Agência Pulse

Jan 2019 - Jun 2021

- Liderança de projetos de branding para clientes de e-commerce, incluindo identidade visual e campanhas de mídia social.
- Integração de ferramentas de análise (Google Analytics, Hotjar) em websites para otimização de UX.
- Automação de fluxos de marketing com WordPress e plugins personalizados em PHP.

## Freelancer em Design e Desenvolvimento Web

Ago 2017 - Dez 2018

- Design e codificação de sites para startups, com foco em mobile-first e SEO.
- Criação de conteúdo visual para redes sociais (Adobe Creative Suite) e integração com CMS como Shopify e Webflow .

## HABILIDADES TÉCNICAS

- Design: Figma, Adobe XD, Photoshop, Illustrator, Prototipagem Interativa
- Front-End: HTML/CSS, JavaScript (ES6+), React.js, Vue.js, SASS
- Back-End Leve: Node.js (Express para APIs simples), Firebase (Firestore, Auth)
- Marketing: Google Analytics, SEO, WordPress, Shopify, Mailchimp
- Ferramentas: Git, Webpack, Jira, Zeplin, A/B Testing

## CERTIFICAÇÕES

- Adobe Certified Expert (ACE) em UX Design (2022)
- Certificação Professional em JavaScript (Codecademy Pro, 2021)
- Google Analytics Individual Qualification (2020)

## IDIOMAS

- Português: Nativo

- Inglês: Fluente (TOEIC: 950/990)

- Espanhol: Intermediário

## PROJETOS DESTACADOS

## Sistema de Design para Plataforma de Educação

- Criação de design system modular (Figma + React) adotado por 20+ times internos.
- Redução de 40% no tempo de desenvolvimento de novas features.

## E-commerce Sustentável "EcoStyle"

- Design de interface e desenvolvimento front-end (Vue.js + Shopify).
- Estratégia de marketing integrada: aumento de 50% em tráfego orgânico em 6 meses.

## INFORMAÇÕES ADICIONAIS

- Voluntariado: Mentoria em design para jovens em comunidades tech (Projeto Design para Todos).
- Prêmios: 2º lugar no Prêmio Nacional de Design Digital (2021) com projeto de acessibilidade web.
- Interesses: Design sustentável, motion graphics, participação em meetups de front-end.

In [16]:
content = result.document.export_to_markdown()
content

'## Alex Costa\n\nE-mail: alex@creativeflow.com.br LinkedIn: linkedin.com/in/alex-costa\n\n## MEU OBJETIVO\n\nProfissional multidisciplinar com 5 anos de experiência integrando design, desenvolvimento front-end e estratégias de marketing digital. Busco aprimorar habilidades em design de interfaces complexas e explorar soluções criativas que unam estética, usabilidade e performance técnica.\n\n## MINHA FORMAÇÃO ACADÊMICA\n\n## Bacharelado em Design Digital\n\nUniversidade Federal do Paraná (UFPR) - Curitiba, PR\n\nMar 2016 - Dez 2020\n\n- Bolsista do programa de inovação em interfaces responsivas.\n- TCC: "Design Systems para Aplicações Escaláveis: Unindo Figma e React".\n\n## Curso Técnico em Marketing Digital\n\nInstituto de Tecnologia e Design (ITEDE) Jan 2014 - Dez 2015\n\n## MINHA EXPERIÊNCIA PROFISSIONAL\n\n## UI/UX Designer &amp; Front-End Developer | DigitalMind Creative Studio\n\nJul 2021 - Atual\n\n- Criação de interfaces para 12+ produtos web e mobile, usando Figma e implementação com React.js e Vue.js .\n- Colaboração com equipes de marketing na construção de landing pages high-conversion (aumento de 35% em taxas de engajamento).\n- Desenvolvimento de componentes reutilizáveis em Storybook para acelerar workflows de design e desenvolvimento.\n\n## Designer de Produto e Marketing | Agência Pulse\n\nJan 2019 - Jun 2021\n\n- Liderança de projetos de branding para clientes de e-commerce, incluindo identidade visual e campanhas de mídia social.\n- Integração de ferramentas de análise (Google Analytics, Hotjar) em websites para otimização de UX.\n- Automação de fluxos de marketing com WordPress e plugins personalizados em PHP.\n\n## Freelancer em Design e Desenvolvimento Web\n\nAgo 2017 - Dez 2018\n\n- Design e codificação de sites para startups, com foco em mobile-first e SEO.\n- Criação de conteúdo visual para redes sociais (Adobe Creative Suite) e integração com CMS como Shopify e Webflow .\n\n## HABILIDADES TÉCNICAS\n\n- Design: Figma, Adobe XD, Photoshop, Illustrator, Prototipagem Interativa\n- Front-End: HTML/CSS, JavaScript (ES6+), React.js, Vue.js, SASS\n- Back-End Leve: Node.js (Express para APIs simples), Firebase (Firestore, Auth)\n- Marketing: Google Analytics, SEO, WordPress, Shopify, Mailchimp\n- Ferramentas: Git, Webpack, Jira, Zeplin, A/B Testing\n\n## CERTIFICAÇÕES\n\n- Adobe Certified Expert (ACE) em UX Design (2022)\n- Certificação Professional em JavaScript (Codecademy Pro, 2021)\n- Google Analytics Individual Qualification (2020)\n\n## IDIOMAS\n\n- Português: Nativo\n\n- Inglês: Fluente (TOEIC: 950/990)\n\n- Espanhol: Intermediário\n\n## PROJETOS DESTACADOS\n\n## Sistema de Design para Plataforma de Educação\n\n- Criação de design system modular (Figma + React) adotado por 20+ times internos.\n- Redução de 40% no tempo de desenvolvimento de novas features.\n\n## E-commerce Sustentável "EcoStyle"\n\n- Design de interface e desenvolvimento front-end (Vue.js + Shopify).\n- Estratégia de marketing integrada: aumento de 50% em tráfego orgânico em 6 meses.\n\n## INFORMAÇÕES ADICIONAIS\n\n- Voluntariado: Mentoria em design para jovens em comunidades tech (Projeto Design para Todos).\n- Prêmios: 2º lugar no Prêmio Nacional de Design Digital (2021) com projeto de acessibilidade web.\n- Interesses: Design sustentável, motion graphics, participação em meetups de front-end.'

In [17]:
source = "https://arxiv.org/pdf/2408.09869"
converter = DocumentConverter()
result = converter.convert(source)
print(result.document.export_to_markdown())

[INFO] 2026-07-20 19:38:17,894 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 19:38:17,896 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 19:38:17,955 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 19:38:17,957 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 19:38:18,400 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 19:38:18,402 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 19:38:18,408 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 19:38:18,408 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 19:38:18,599 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 19:38:18,602 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 19:38:18,771 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-07-20 19:38:18,773 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

<!-- image -->

## Docling Technical Report

## Version 1.0

Christoph Auer Maksym Lysak Ahmed Nassar Michele Dolfi Nikolaos Livathinos Panos Vagenas Cesar Berrospi Ramis Matteo Omenetti Fabian Lindlbauer Kasper Dinkla Lokesh Mishra Yusik Kim Shubham Gupta Rafael Teixeira de Lima Valery Weber Lucas Morin Ingmar Meijer Viktor Kuropiatnyk Peter W. J. Staar

AI4K Group, IBM Research R¨ uschlikon, Switzerland

## Abstract

This technical report introduces Docling , an easy to use, self-contained, MITlicensed open-source package for PDF document conversion. It is powered by state-of-the-art specialized AI models for layout analysis (DocLayNet) and table structure recognition (TableFormer), and runs efficiently on commodity hardware in a small resource budget. The code interface allows for easy extensibility and addition of new features and models.

## 1 Introduction

Converting PDF documents back into a machine-processable format has been a major challenge for decades due to their huge variability in formats, weak standardization and printing-optimized characteristic, which discards most structural features and metadata. With the advent of LLMs and popular application patterns such as retrieval-augmented generation (RAG), leveraging the rich content embedded in PDFs has become ever more relevant. In the past decade, several powerful document understanding solutions have emerged on the market, most of which are commercial software, cloud offerings [3] and most recently, multi-modal vision-language models. As of today, only a handful of open-source tools cover PDF conversion, leaving a significant feature and quality gap to proprietary solutions.

With Docling , we open-source a very capable and efficient document conversion tool which builds on the powerful, specialized AI models and datasets for layout analysis and table structure recognition we developed and presented in the recent past [12, 13, 9]. Docling is designed as a simple, self-contained python library with permissive license, running entirely locally on commodity hardware. Its code architecture allows for easy extensibility and addition of new features and models.

Here is what Docling delivers today:

- Converts PDF documents to JSON or Markdown format, stable and lightning fast
- Understands detailed page layout, reading order, locates figures and recovers table structures
- Extracts metadata from the document, such as title, authors, references and language
- Optionally applies OCR, e.g. for scanned PDFs
- Can be configured to be optimal for batch-mode (i.e high throughput, low time-to-solution)
- or interactive mode (compromise on efficiency, low time-to-solution)
- Can leverage different accelerators (GPU, MPS, etc).

## 2 Getting Started

To use Docling, you can simply install the docling package from PyPI. Documentation and examples are available in our GitHub repository at github.com/DS4SD/docling. All required model assets 1 are downloaded to a local huggingface datasets cache on first use, unless you choose to pre-install the model assets in advance.

Docling provides an easy code interface to convert PDF documents from file system, URLs or binary streams, and retrieve the output in either JSON or Markdown format. For convenience, separate methods are offered to convert single documents or batches of documents. A basic usage example is illustrated below. Further examples are available in the Doclign code repository.

from docling.document\_converter import DocumentConverter

```
source = "https://arxiv.org/pdf/2206.01062" # PDF path or URL converter = DocumentConverter() result = converter.convert_single(source) print(result.render_as_markdown()) # output: "## DocLayNet: A Large Human -Annotated Dataset for Document -Layout Analysis [...]"
```

Optionally, you can configure custom pipeline features and runtime options, such as turning on or off features (e.g. OCR, table structure recognition), enforcing limits on the input document size, and defining the budget of CPU threads. Advanced usage examples and options are documented in the README file. Docling also provides a Dockerfile to demonstrate how to install and run it inside a container.

## 3 Processing pipeline

Docling implements a linear pipeline of operations, which execute sequentially on each given document (see Fig. 1). Each document is first parsed by a PDF backend, which retrieves the programmatic text tokens, consisting of string content and its coordinates on the page, and also renders a bitmap image of each page to support downstream operations. Then, the standard model pipeline applies a sequence of AI models independently on every page in the document to extract features and content, such as layout and table structures. Finally, the results from all pages are aggregated and passed through a post-processing stage, which augments metadata, detects the document language, infers reading-order and eventually assembles a typed document object which can be serialized to JSON or Markdown.

## 3.1 PDF backends

Two basic requirements to process PDF documents in our pipeline are a) to retrieve all text content and their geometric coordinates on each page and b) to render the visual representation of each page as it would appear in a PDF viewer. Both these requirements are encapsulated in Docling's PDF backend interface. While there are several open-source PDF parsing libraries available for python, we faced major obstacles with all of them for different reasons, among which were restrictive licensing (e.g. pymupdf [7]), poor speed or unrecoverable quality issues, such as merged text cells across far-apart text tokens or table columns (pypdfium, PyPDF) [15, 14].

[1 see huggingface.co/ds4sd/docling-models/](https://huggingface.co/ds4sd/docling-models/)

Figure 1: Sketch of Docling's default processing pipeline. The inner part of the model pipeline is easily customizable and extensible.

<!-- image -->

We therefore decided to provide multiple backend choices, and additionally open-source a custombuilt PDF parser, which is based on the low-level qpdf [4] library. It is made available in a separate package named docling-parse and powers the default PDF backend in Docling. As an alternative, we provide a PDF backend relying on pypdfium , which may be a safe backup choice in certain cases, e.g. if issues are seen with particular font encodings.

## 3.2 AI models

As part of Docling, we initially release two highly capable AI models to the open-source community, which have been developed and published recently by our team. The first model is a layout analysis model, an accurate object-detector for page elements [13]. The second model is TableFormer [12, 9], a state-of-the-art table structure recognition model. We provide the pre-trained weights (hosted on huggingface) and a separate package for the inference code as docling-ibm-models . Both models are also powering the open-access deepsearch-experience, our cloud-native service for knowledge exploration tasks.

## Layout Analysis Model

Our layout analysis model is an object-detector which predicts the bounding-boxes and classes of various elements on the image of a given page. Its architecture is derived from RT-DETR [16] and re-trained on DocLayNet [13], our popular human-annotated dataset for document-layout analysis, among other proprietary datasets. For inference, our implementation relies on the onnxruntime [5].

The Docling pipeline feeds page images at 72 dpi resolution, which can be processed on a single CPU with sub-second latency. All predicted bounding-box proposals for document elements are post-processed to remove overlapping proposals based on confidence and size, and then intersected with the text tokens in the PDF to group them into meaningful and complete units such as paragraphs, section titles, list items, captions, figures or tables.

## Table Structure Recognition

The TableFormer model [12], first published in 2022 and since refined with a custom structure token language [9], is a vision-transformer model for table structure recovery. It can predict the logical row and column structure of a given table based on an input image, and determine which table cells belong to column headers, row headers or the table body. Compared to earlier approaches, TableFormer handles many characteristics of tables, such as partial or no borderlines, empty cells, rows or columns, cell spans and hierarchy both on column-heading or row-heading level, tables with inconsistent indentation or alignment and other complexities. For inference, our implementation relies on PyTorch [2].

The Docling pipeline feeds all table objects detected in the layout analysis to the TableFormer model, by providing an image-crop of the table and the included text cells. TableFormer structure predictions are matched back to the PDF cells in post-processing to avoid expensive re-transcription text in the table image. Typical tables require between 2 and 6 seconds to be processed on a standard CPU, strongly depending on the amount of included table cells.

## OCR

Docling provides optional support for OCR, for example to cover scanned PDFs or content in bitmaps images embedded on a page. In our initial release, we rely on EasyOCR [1], a popular thirdparty OCR library with support for many languages. Docling, by default, feeds a high-resolution page image (216 dpi) to the OCR engine, to allow capturing small print detail in decent quality. While EasyOCR delivers reasonable transcription quality, we observe that it runs fairly slow on CPU (upwards of 30 seconds per page).

We are actively seeking collaboration from the open-source community to extend Docling with additional OCR backends and speed improvements.

## 3.3 Assembly

In the final pipeline stage, Docling assembles all prediction results produced on each page into a well-defined datatype that encapsulates a converted document, as defined in the auxiliary package docling-core . The generated document object is passed through a post-processing model which leverages several algorithms to augment features, such as detection of the document language, correcting the reading order, matching figures with captions and labelling metadata such as title, authors and references. The final output can then be serialized to JSON or transformed into a Markdown representation at the users request.

## 3.4 Extensibility

Docling provides a straight-forward interface to extend its capabilities, namely the model pipeline. A model pipeline constitutes the central part in the processing, following initial document parsing and preceding output assembly, and can be fully customized by sub-classing from an abstract baseclass ( BaseModelPipeline ) or cloning the default model pipeline. This effectively allows to fully customize the chain of models, add or replace models, and introduce additional pipeline configuration parameters. To use a custom model pipeline, the custom pipeline class to instantiate can be provided as an argument to the main document conversion methods. We invite everyone in the community to propose additional or alternative models and improvements.

Implementations of model classes must satisfy the python Callable interface. The \_\_call\_\_ method must accept an iterator over page objects, and produce another iterator over the page objects which were augmented with the additional features predicted by the model, by extending the provided PagePredictions data model accordingly.

## 4 Performance

In this section, we establish some reference numbers for the processing speed of Docling and the resource budget it requires. All tests in this section are run with default options on our standard test set distributed with Docling, which consists of three papers from arXiv and two IBM Redbooks, with a total of 225 pages. Measurements were taken using both available PDF backends on two different hardware systems: one MacBook Pro M3 Max, and one bare-metal server running Ubuntu 20.04 LTS on an Intel Xeon E5-2690 CPU. For reproducibility, we fixed the thread budget (through setting OMP NUM THREADS environment variable ) once to 4 (Docling default) and once to 16 (equal to full core count on the test hardware). All results are shown in Table 1.

If you need to run Docling in very low-resource environments, please consider configuring the pypdfium backend. While it is faster and more memory efficient than the default docling-parse backend, it will come at the expense of worse quality results, especially in table structure recovery.

Establishing GPU acceleration support for the AI models is currently work-in-progress and largely untested, but may work implicitly when CUDA is available and discovered by the onnxruntime and torch runtimes backing the Docling pipeline. We will deliver updates on this topic at in a future version of this report.

Table 1: Runtime characteristics of Docling with the standard model pipeline and settings, on our test dataset of 225 pages, on two different systems. OCR is disabled. We show the time-to-solution (TTS), computed throughput in pages per second, and the peak memory used (resident set size) for both the Docling-native PDF backend and for the pypdfium backend, using 4 and 16 threads.

| CPU                     | Thread budget   | native backend   | native backend   | native backend   | pypdfium backend   | pypdfium backend   | pypdfium backend   |
|-------------------------|-----------------|------------------|------------------|------------------|--------------------|--------------------|--------------------|
|                         |                 | TTS              | Pages/s          | Mem              | TTS                | Pages/s            | Mem                |
| Apple M3 Max (16 cores) | 4 16            | 177 s 167 s      | 1.27 1.34        | 6.20 GB          | 103 s 92 s         | 2.18 2.45          | 2.56 GB            |
| Intel(R) Xeon E5-2690   | 4 16            | 375 s 244 s      | 0.60 0.92        | 6.16 GB          | 239 s 143 s        | 0.94 1.57          | 2.42 GB            |

## 5 Applications

Thanks to the high-quality, richly structured document conversion achieved by Docling, its output qualifies for numerous downstream applications. For example, Docling can provide a base for detailed enterprise document search, passage retrieval or classification use-cases, or support knowledge extraction pipelines, allowing specific treatment of different structures in the document, such as tables, figures, section structure or references. For popular generative AI application patterns, such as retrieval-augmented generation (RAG), we provide quackling , an open-source package which capitalizes on Docling's feature-rich document output to enable document-native optimized vector embedding and chunking. It plugs in seamlessly with LLM frameworks such as LlamaIndex [8]. Since Docling is fast, stable and cheap to run, it also makes for an excellent choice to build document-derived datasets. With its powerful table structure recognition, it provides significant benefit to automated knowledge-base construction [11, 10]. Docling is also integrated within the open IBM data prep kit [6], which implements scalable data transforms to build large-scale multi-modal training datasets.

## 6 Future work and contributions

Docling is designed to allow easy extension of the model library and pipelines. In the future, we plan to extend Docling with several more models, such as a figure-classifier model, an equationrecognition model, a code-recognition model and more. This will help improve the quality of conversion for specific types of content, as well as augment extracted document metadata with additional information. Further investment into testing and optimizing GPU acceleration as well as improving the Docling-native PDF backend are on our roadmap, too.

We encourage everyone to propose or implement additional features and models, and will gladly take your inputs and contributions under review . The codebase of Docling is open for use and contribution, under the MIT license agreement and in alignment with our contributing guidelines included in the Docling repository. If you use Docling in your projects, please consider citing this technical report.

## References

- [1] J. AI. Easyocr: Ready-to-use ocr with 80+ supported languages. https://github.com/ JaidedAI/EasyOCR , 2024. Version: 1.7.0.
- [2] J. Ansel, E. Yang, H. He, N. Gimelshein, A. Jain, M. Voznesensky, B. Bao, P. Bell, D. Berard, E. Burovski, G. Chauhan, A. Chourdia, W. Constable, A. Desmaison, Z. DeVito, E. Ellison, W. Feng, J. Gong, M. Gschwind, B. Hirsh, S. Huang, K. Kalambarkar, L. Kirsch, M. Lazos, M. Lezcano, Y. Liang, J. Liang, Y. Lu, C. Luk, B. Maher, Y. Pan, C. Puhrsch, M. Reso, M. Saroufim, M. Y. Siraichi, H. Suk, M. Suo, P. Tillet, E. Wang, X. Wang, W. Wen, S. Zhang, X. Zhao, K. Zhou, R. Zou, A. Mathews, G. Chanan, P. Wu, and S. Chintala. Pytorch 2: Faster

machine learning through dynamic python bytecode transformation and graph compilation. In Proceedings of the 29th ACM International Conference on Architectural Support for Programming Languages and Operating Systems, Volume 2 (ASPLOS '24) . ACM, 4 2024. doi: 10.1145/3620665.3640366. URL https://pytorch.org/assets/pytorch2-2.pdf .

- [3] C. Auer, M. Dolfi, A. Carvalho, C. B. Ramis, and P. W. Staar. Delivering document conversion as a cloud service with high throughput and responsiveness. In 2022 IEEE 15th International Conference on Cloud Computing (CLOUD) , pages 363-373. IEEE, 2022.
- [4] J. Berkenbilt. Qpdf: A content-preserving pdf document transformer, 2024. URL https: //github.com/qpdf/qpdf .
- [5] O. R. developers. Onnx runtime. https://onnxruntime.ai/ , 2024. Version: 1.18.1.
- [6] IBM. Data Prep Kit: a community project to democratize and accelerate unstructured data preparation for LLM app developers, 2024. URL https://github.com/IBM/ data-prep-kit .
- [7] [A. S. Inc. PyMuPDF, 2024. URL https://github.com/pymupdf/PyMuPDF .](https://github.com/pymupdf/PyMuPDF)
- [8] [J. Liu. LlamaIndex, 11 2022. URL https://github.com/jerryjliu/llama\_index .](https://github.com/jerryjliu/llama_index)
- [9] M. Lysak, A. Nassar, N. Livathinos, C. Auer, and P. Staar. Optimized Table Tokenization for Table Structure Recognition. In Document Analysis and Recognition - ICDAR 2023: 17th International Conference, San Jos´ e, CA, USA, August 21-26, 2023, Proceedings, Part II , pages 37-50, Berlin, Heidelberg, Aug. 2023. Springer-Verlag. ISBN 978-3-031-41678-1. doi: 10. 1007/978-3-031-41679-8 3. URL https://doi.org/10.1007/978-3-031-41679-8\_3 .
- [10] L. Mishra, S. Dhibi, Y. Kim, C. Berrospi Ramis, S. Gupta, M. Dolfi, and P. Staar. Statements: Universal information extraction from tables with large language models for ESG KPIs. In D. Stammbach, J. Ni, T. Schimanski, K. Dutia, A. Singh, J. Bingler, C. Christiaen, N. Kushwaha, V. Muccione, S. A. Vaghefi, and M. Leippold, editors, Proceedings of the 1st Workshop on Natural Language Processing Meets Climate Change (ClimateNLP 2024) , pages 193-214, Bangkok, Thailand, Aug. 2024. Association for Computational Linguistics. URL https://aclanthology.org/2024.climatenlp-1.15 .
- [11] L. Morin, V. Weber, G. I. Meijer, F. Yu, and P. W. J. Staar. Patcid: an open-access dataset of chemical structures in patent documents. Nature Communications , 15(1):6532, August 2024. ISSN 2041-1723. doi: 10.1038/s41467-024-50779-y. URL https://doi.org/10.1038/ s41467-024-50779-y .
- [12] A. Nassar, N. Livathinos, M. Lysak, and P. Staar. Tableformer: Table structure understanding with transformers. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition , pages 4614-4623, 2022.
- [13] B. Pfitzmann, C. Auer, M. Dolfi, A. S. Nassar, and P. Staar. Doclaynet: a large humanannotated dataset for document-layout segmentation. pages 3743-3751, 2022.

### Docling com LangChain

In [18]:
!pip install -q langchain-docling

In [19]:
from langchain_docling import DoclingLoader

loader = DoclingLoader(path)
docs = loader.load()

[INFO] 2026-07-20 19:44:56,747 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 19:44:56,750 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 19:44:56,807 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 19:44:56,809 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 19:44:57,578 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 19:44:57,580 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 19:44:57,586 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 19:44:57,587 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 19:44:57,709 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 19:44:57,711 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 19:44:57,801 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-07-20 19:44:57,802 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

In [20]:
for d in docs[:3]:
  print(f"- {d.page_content=}")

- d.page_content='Alex Costa\nE-mail: alex@creativeflow.com.br LinkedIn: linkedin.com/in/alex-costa'
- d.page_content='MEU OBJETIVO\nProfissional multidisciplinar com 5 anos de experiência integrando design, desenvolvimento front-end e estratégias de marketing digital. Busco aprimorar habilidades em design de interfaces complexas e explorar soluções criativas que unam estética, usabilidade e performance técnica.'
- d.page_content='Bacharelado em Design Digital\nUniversidade Federal do Paraná (UFPR) - Curitiba, PR\nMar 2016 - Dez 2020\n- Bolsista do programa de inovação em interfaces responsivas.\n- TCC: "Design Systems para Aplicações Escaláveis: Unindo Figma e React".'

## Carregando a LLM

### Groq

In [21]:
import os
import getpass
os.environ["GROQ_API_KEY"] = getpass.getpass()

··········

In [22]:
from langchain_groq import ChatGroq

def load_llm(id_model, temperature):
  llm = ChatGroq(
      model=id_model,
      temperature=temperature,
      max_tokens=None,
      timeout=None,
      max_retries=2,
  )
  return llm

In [23]:
id_model = "deepseek-r1-distill-llama-70b"  # @param {type:"string"}
temperature = 0.7 #@param {type:"slider", min:0.1, max:1.5, step:0.1}

llm = load_llm(id_model, temperature)

### OpenAI

In [27]:
!pip install langchain-openai -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 kB 1.4 MB/s eta 0:00:00

In [24]:
os.environ["OPENAI_API_KEY"] = getpass.getpass()

··········

In [29]:
from langchain_openai import ChatOpenAI

def load_llm_openAI(temperature = 1, id_model = "gpt-5-mini"):
  llm = ChatOpenAI(
      model=id_model,
      temperature=temperature,
      max_tokens=None,
      timeout=None,
      max_retries=2,
  )
  return llm

In [34]:
llm = load_llm_openAI()

### OpenAI

## Testes iniciais

In [30]:
prompt = f"""
Resuma esse currículo em 1 parágrafo:
{content}
"""

In [31]:
prompt

'\nResuma esse currículo em 1 parágrafo:\n## Alex Costa\n\nE-mail: alex@creativeflow.com.br LinkedIn: linkedin.com/in/alex-costa\n\n## MEU OBJETIVO\n\nProfissional multidisciplinar com 5 anos de experiência integrando design, desenvolvimento front-end e estratégias de marketing digital. Busco aprimorar habilidades em design de interfaces complexas e explorar soluções criativas que unam estética, usabilidade e performance técnica.\n\n## MINHA FORMAÇÃO ACADÊMICA\n\n## Bacharelado em Design Digital\n\nUniversidade Federal do Paraná (UFPR) - Curitiba, PR\n\nMar 2016 - Dez 2020\n\n- Bolsista do programa de inovação em interfaces responsivas.\n- TCC: "Design Systems para Aplicações Escaláveis: Unindo Figma e React".\n\n## Curso Técnico em Marketing Digital\n\nInstituto de Tecnologia e Design (ITEDE) Jan 2014 - Dez 2015\n\n## MINHA EXPERIÊNCIA PROFISSIONAL\n\n## UI/UX Designer &amp; Front-End Developer | DigitalMind Creative Studio\n\nJul 2021 - Atual\n\n- Criação de interfaces para 12+ produtos web e mobile, usando Figma e implementação com React.js e Vue.js .\n- Colaboração com equipes de marketing na construção de landing pages high-conversion (aumento de 35% em taxas de engajamento).\n- Desenvolvimento de componentes reutilizáveis em Storybook para acelerar workflows de design e desenvolvimento.\n\n## Designer de Produto e Marketing | Agência Pulse\n\nJan 2019 - Jun 2021\n\n- Liderança de projetos de branding para clientes de e-commerce, incluindo identidade visual e campanhas de mídia social.\n- Integração de ferramentas de análise (Google Analytics, Hotjar) em websites para otimização de UX.\n- Automação de fluxos de marketing com WordPress e plugins personalizados em PHP.\n\n## Freelancer em Design e Desenvolvimento Web\n\nAgo 2017 - Dez 2018\n\n- Design e codificação de sites para startups, com foco em mobile-first e SEO.\n- Criação de conteúdo visual para redes sociais (Adobe Creative Suite) e integração com CMS como Shopify e Webflow .\n\n## HABILIDADES TÉCNICAS\n\n- Design: Figma, Adobe XD, Photoshop, Illustrator, Prototipagem Interativa\n- Front-End: HTML/CSS, JavaScript (ES6+), React.js, Vue.js, SASS\n- Back-End Leve: Node.js (Express para APIs simples), Firebase (Firestore, Auth)\n- Marketing: Google Analytics, SEO, WordPress, Shopify, Mailchimp\n- Ferramentas: Git, Webpack, Jira, Zeplin, A/B Testing\n\n## CERTIFICAÇÕES\n\n- Adobe Certified Expert (ACE) em UX Design (2022)\n- Certificação Professional em JavaScript (Codecademy Pro, 2021)\n- Google Analytics Individual Qualification (2020)\n\n## IDIOMAS\n\n- Português: Nativo\n\n- Inglês: Fluente (TOEIC: 950/990)\n\n- Espanhol: Intermediário\n\n## PROJETOS DESTACADOS\n\n## Sistema de Design para Plataforma de Educação\n\n- Criação de design system modular (Figma + React) adotado por 20+ times internos.\n- Redução de 40% no tempo de desenvolvimento de novas features.\n\n## E-commerce Sustentável "EcoStyle"\n\n- Design de interface e desenvolvimento front-end (Vue.js + Shopify).\n- Estratégia de marketing integrada: aumento de 50% em tráfego orgânico em 6 meses.\n\n## INFORMAÇÕES ADICIONAIS\n\n- Voluntariado: Mentoria em design para jovens em comunidades tech (Projeto Design para Todos).\n- Prêmios: 2º lugar no Prêmio Nacional de Design Digital (2021) com projeto de acessibilidade web.\n- Interesses: Design sustentável, motion graphics, participação em meetups de front-end.\n'

In [35]:
output = llm.invoke(prompt)
output.content

'Alex Costa é um profissional multidisciplinar com 5 anos de experiência integrando UI/UX, front‑end e marketing digital; bacharel em Design Digital (UFPR) com TCC sobre Design Systems e atualmente atua como UI/UX Designer & Front‑End Developer na DigitalMind Creative Studio (desde jul/2021), tendo passado por Agência Pulse e trabalhos freelance. Possui forte domínio de Figma, React.js, Vue.js, HTML/CSS, JavaScript (ES6+), SASS e ferramentas de marketing (Google Analytics, SEO, WordPress/Shopify), criou interfaces para +12 produtos, desenvolveu componentes em Storybook, colaborou em landing pages que aumentaram engajamento em 35% e implementou um design system (Figma + React) adotado por 20+ times que reduziu em 40% o tempo de desenvolvimento; destaque também no projeto EcoStyle (front‑end e estratégia que gerou +50% de tráfego orgânico). Certificações incluem Adobe ACE em UX, certificação profissional em JavaScript e Google Analytics IQ; fala português nativo, inglês fluente (TOEIC 950) e espanhol intermediário; busca aprofundar-se em design de interfaces complexas unindo estética, usabilidade e performance técnica.'

## Processamento e exibição do resultado

In [36]:
def format_res(res, return_thinking=False):
  res = res.strip()

  if return_thinking:
    res = res.replace("<think>", "[pensando...] ")
    res = res.replace("</think>", "\n---\n")

  else:
    if "</think>" in res:
      res = res.split("</think>")[-1].strip()

  return res

def show_res(res):
    from IPython.display import Markdown
    display(Markdown(res))

In [37]:
res = format_res(output.content)

show_res(res)

Alex Costa é um profissional multidisciplinar com 5 anos de experiência integrando UI/UX, front‑end e marketing digital; bacharel em Design Digital (UFPR) com TCC sobre Design Systems e atualmente atua como UI/UX Designer & Front‑End Developer na DigitalMind Creative Studio (desde jul/2021), tendo passado por Agência Pulse e trabalhos freelance. Possui forte domínio de Figma, React.js, Vue.js, HTML/CSS, JavaScript (ES6+), SASS e ferramentas de marketing (Google Analytics, SEO, WordPress/Shopify), criou interfaces para +12 produtos, desenvolveu componentes em Storybook, colaborou em landing pages que aumentaram engajamento em 35% e implementou um design system (Figma + React) adotado por 20+ times que reduziu em 40% o tempo de desenvolvimento; destaque também no projeto EcoStyle (front‑end e estratégia que gerou +50% de tráfego orgânico). Certificações incluem Adobe ACE em UX, certificação profissional em JavaScript e Google Analytics IQ; fala português nativo, inglês fluente (TOEIC 950) e espanhol intermediário; busca aprofundar-se em design de interfaces complexas unindo estética, usabilidade e performance técnica.

In [38]:
show_res(format_res(output.content, return_thinking=True))

Alex Costa é um profissional multidisciplinar com 5 anos de experiência integrando UI/UX, front‑end e marketing digital; bacharel em Design Digital (UFPR) com TCC sobre Design Systems e atualmente atua como UI/UX Designer & Front‑End Developer na DigitalMind Creative Studio (desde jul/2021), tendo passado por Agência Pulse e trabalhos freelance. Possui forte domínio de Figma, React.js, Vue.js, HTML/CSS, JavaScript (ES6+), SASS e ferramentas de marketing (Google Analytics, SEO, WordPress/Shopify), criou interfaces para +12 produtos, desenvolveu componentes em Storybook, colaborou em landing pages que aumentaram engajamento em 35% e implementou um design system (Figma + React) adotado por 20+ times que reduziu em 40% o tempo de desenvolvimento; destaque também no projeto EcoStyle (front‑end e estratégia que gerou +50% de tráfego orgânico). Certificações incluem Adobe ACE em UX, certificação profissional em JavaScript e Google Analytics IQ; fala português nativo, inglês fluente (TOEIC 950) e espanhol intermediário; busca aprofundar-se em design de interfaces complexas unindo estética, usabilidade e performance técnica.

## Construindo o prompt

### Base do Prompt

In [39]:
from langchain_core.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    MessagesPlaceholder,
)

In [41]:
prompt_template = ChatPromptTemplate.from_template("""
Você é um especialista em Recursos Humanos com vasta experiência em análise de currículos.
Sua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.
Responda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses.
Não adicione explicações ou anotações fora do JSON.
Schema desejado:
{schema}

---

Currículo a ser analisado:
'{cv}'
""")

In [42]:
prompt_template

ChatPromptTemplate(input_variables=['cv', 'schema'], input_types={}, partial_variables={}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['cv', 'schema'], input_types={}, partial_variables={}, template="\nVocê é um especialista em Recursos Humanos com vasta experiência em análise de currículos.\nSua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.\nResponda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses.\nNão adicione explicações ou anotações fora do JSON.\nSchema desejado:\n{schema}\n\n---\n\nCurrículo a ser analisado:\n'{cv}'\n"), additional_kwargs={})])

### Definindo o Schema para análise de currículos

A seguir está o schema com os campos que queremos extrair de cada currículo analisado, baseado nos campos:

```
- Nome completo
- Área de atuação
- Resumo do perfil
- Principais competências
- Educação
- Sugestão de pergunta para entrevista

```

In [43]:
schema = """
{
  "name": "Nome completo do candidato",
  "area": "Área ou setor principal onde o candidato atua",
  "summary": "Resumo objetivo sobre o perfil profissional do candidato",
  "skills": ["competência 1", "competência 2", "..."],
  "education": "Resumo da formação acadêmica mais relevante",
  "interview_questions": "Pergunta útil para entrevista com base no currículo, para esclarecer algum ponto ou explorar melhor",
}
"""

In [44]:
chain = prompt_template | llm
output = chain.invoke({"schema": schema, "cv": content})

show_res(output.content)

{
  "name": "Alex Costa",
  "area": "Design de UI/UX e Front-end (com integração a Marketing Digital)",
  "summary": "Profissional multidisciplinar com 5 anos de experiência integrando design de interfaces, desenvolvimento front-end e estratégias de marketing digital; experiência em design systems (Figma + React), criação de interfaces web/mobile, componentes reutilizáveis (Storybook) e otimização de conversão e SEO.",
  "skills": [
    "Design de interfaces (Figma, Adobe XD)",
    "Design system (modular) e prototipagem interativa",
    "React.js",
    "Vue.js",
    "HTML/CSS",
    "JavaScript (ES6+)",
    "SASS",
    "Storybook",
    "Node.js (Express) e Firebase (Firestore, Auth)",
    "Photoshop e Illustrator",
    "SEO e Google Analytics",
    "Hotjar e análise de comportamento",
    "WordPress, Shopify e automação de marketing",
    "A/B Testing",
    "Git, Webpack, Jira",
    "Criação de landing pages de alta conversão",
    "Acessibilidade web"
  ],
  "education": "Bacharelado em Design Digital — Universidade Federal do Paraná (UFPR), Mar 2016 – Dez 2020 (TCC: Design Systems para Aplicações Escaláveis). Curso Técnico em Marketing Digital — Instituto de Tecnologia e Design (ITEDE), Jan 2014 – Dez 2015.",
  "interview_questions": "Pode descrever detalhadamente seu papel na criação e manutenção do design system (Figma + React) adotado por 20+ times? Quais componentes você implementou em Storybook, como foi a colaboração com times de engenharia e produto, e como vocês mensuraram a redução de 40% no tempo de desenvolvimento?"
}

## Reunindo em uma função

In [45]:
def process_cv(schema, content):
  chain = prompt_template | llm
  output = chain.invoke({"schema": schema, "cv": content})

  res = format_res(output.content)

  return output, res

In [46]:
output, res = process_cv(schema, content)

In [47]:
output

AIMessage(content='{\n  "name": "Alex Costa",\n  "area": "UI/UX Design e Front-end Development (Design de Produto, Interfaces e Marketing Digital)",\n  "summary": "Profissional multidisciplinar com ~5 anos de experiência integrando design de interfaces, desenvolvimento front-end e estratégias de marketing digital. Experiência em criação e implementação de design systems (Figma + React), desenvolvimento de componentes reutilizáveis (Storybook), construção de landing pages de alta conversão e automação/otimização de UX com métricas mensuráveis.",\n  "skills": [\n    "Figma",\n    "Design Systems",\n    "Adobe XD",\n    "Photoshop",\n    "Illustrator",\n    "Prototipagem interativa",\n    "HTML/CSS",\n    "JavaScript (ES6+)",\n    "React.js",\n    "Vue.js",\n    "SASS",\n    "Storybook",\n    "Node.js (Express)",\n    "Firebase (Firestore, Auth)",\n    "Google Analytics",\n    "Hotjar",\n    "SEO",\n    "WordPress",\n    "Shopify",\n    "Mailchimp",\n    "Git",\n    "Webpack",\n    "Jira",\n    "Zeplin",\n    "A/B Testing",\n    "Branding",\n    "Mobile-first",\n    "Acessibilidade"\n  ],\n  "education": "Bacharelado em Design Digital — Universidade Federal do Paraná (UFPR), Mar 2016 - Dez 2020. TCC: \\"Design Systems para Aplicações Escaláveis: Unindo Figma e React\\". Curso Técnico em Marketing Digital — Instituto de Tecnologia e Design (ITEDE), Jan 2014 - Dez 2015.",\n  "interview_questions": "Pode descrever em detalhes o design system que você criou (estrutura de tokens, biblioteca de componentes, integração com Storybook e fluxo de manutenção)? Como foi o processo de adoção pelos >20 times e que métricas ou práticas específicas levaram à redução de 40% no tempo de desenvolvimento?"\n}', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 875, 'prompt_tokens': 996, 'total_tokens': 1871, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 448, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5-mini-2025-08-07', 'system_fingerprint': None, 'id': 'chatcmpl-E3oX1Gr7gTIeC4xA4CYoiJnsIVkRz', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019f8122-476d-7f30-8b1c-80c8011f7938-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 996, 'output_tokens': 875, 'total_tokens': 1871, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 448}})

In [48]:
res

'{\n  "name": "Alex Costa",\n  "area": "UI/UX Design e Front-end Development (Design de Produto, Interfaces e Marketing Digital)",\n  "summary": "Profissional multidisciplinar com ~5 anos de experiência integrando design de interfaces, desenvolvimento front-end e estratégias de marketing digital. Experiência em criação e implementação de design systems (Figma + React), desenvolvimento de componentes reutilizáveis (Storybook), construção de landing pages de alta conversão e automação/otimização de UX com métricas mensuráveis.",\n  "skills": [\n    "Figma",\n    "Design Systems",\n    "Adobe XD",\n    "Photoshop",\n    "Illustrator",\n    "Prototipagem interativa",\n    "HTML/CSS",\n    "JavaScript (ES6+)",\n    "React.js",\n    "Vue.js",\n    "SASS",\n    "Storybook",\n    "Node.js (Express)",\n    "Firebase (Firestore, Auth)",\n    "Google Analytics",\n    "Hotjar",\n    "SEO",\n    "WordPress",\n    "Shopify",\n    "Mailchimp",\n    "Git",\n    "Webpack",\n    "Jira",\n    "Zeplin",\n    "A/B Testing",\n    "Branding",\n    "Mobile-first",\n    "Acessibilidade"\n  ],\n  "education": "Bacharelado em Design Digital — Universidade Federal do Paraná (UFPR), Mar 2016 - Dez 2020. TCC: \\"Design Systems para Aplicações Escaláveis: Unindo Figma e React\\". Curso Técnico em Marketing Digital — Instituto de Tecnologia e Design (ITEDE), Jan 2014 - Dez 2015.",\n  "interview_questions": "Pode descrever em detalhes o design system que você criou (estrutura de tokens, biblioteca de componentes, integração com Storybook e fluxo de manutenção)? Como foi o processo de adoção pelos >20 times e que métricas ou práticas específicas levaram à redução de 40% no tempo de desenvolvimento?"\n}'

## Validando a saída

In [49]:
import json

def parse_res_llm(response_text: str, required_fields: list) -> dict:
  try:
    if "</think>" in response_text:
      response_text = response_text.split("</think>")[-1].strip() # efetivamente descarta tudo que veio antes e a própria tag </think>.

    start_idx = response_text.find("{")
    end_idx = response_text.find("}") + 1
    if start_idx == -1 or end_idx == 0:
      raise json.JSONDecodeError("Nenhum JSON encontrado na resposta", response_text, 0)

    json_str = response_text[start_idx:end_idx]
    info_cv = json.loads(json_str)

    for field in required_fields:
      if field not in info_cv:
        info_cv[field] = []

    return info_cv

  except json.JSONDecodeError:
    return

In [50]:
fields = [
    "name",
    "area",
    "summary",
    "skills",
    "education",
    "interview_questions",
]

In [51]:
structured_data = parse_res_llm(res, fields)
structured_data

{'name': 'Alex Costa',
 'area': 'UI/UX Design e Front-end Development (Design de Produto, Interfaces e Marketing Digital)',
 'summary': 'Profissional multidisciplinar com ~5 anos de experiência integrando design de interfaces, desenvolvimento front-end e estratégias de marketing digital. Experiência em criação e implementação de design systems (Figma + React), desenvolvimento de componentes reutilizáveis (Storybook), construção de landing pages de alta conversão e automação/otimização de UX com métricas mensuráveis.',
 'skills': ['Figma',
  'Design Systems',
  'Adobe XD',
  'Photoshop',
  'Illustrator',
  'Prototipagem interativa',
  'HTML/CSS',
  'JavaScript (ES6+)',
  'React.js',
  'Vue.js',
  'SASS',
  'Storybook',
  'Node.js (Express)',
  'Firebase (Firestore, Auth)',
  'Google Analytics',
  'Hotjar',
  'SEO',
  'WordPress',
  'Shopify',
  'Mailchimp',
  'Git',
  'Webpack',
  'Jira',
  'Zeplin',
  'A/B Testing',
  'Branding',
  'Mobile-first',
  'Acessibilidade'],
 'education': 'Bacharelado em Design Digital — Universidade Federal do Paraná (UFPR), Mar 2016 - Dez 2020. TCC: "Design Systems para Aplicações Escaláveis: Unindo Figma e React". Curso Técnico em Marketing Digital — Instituto de Tecnologia e Design (ITEDE), Jan 2014 - Dez 2015.',
 'interview_questions': 'Pode descrever em detalhes o design system que você criou (estrutura de tokens, biblioteca de componentes, integração com Storybook e fluxo de manutenção)? Como foi o processo de adoção pelos >20 times e que métricas ou práticas específicas levaram à redução de 40% no tempo de desenvolvimento?'}

### Salvando e lendo os dados estruturados

In [52]:
path_json = "curriculos.json"

def save_json_cv(result, path_json):
  with open(path_json, "w", encoding="utf-8") as f:
    json.dump(result, f, indent=2, ensure_ascii=False)

save_json_cv(structured_data, path_json)


### Carregando o conteúdo do arquivo JSON

In [53]:
def load_json_cv(path_json):
  with open(path_json, "r", encoding="utf-8") as f:
    return json.load(f)

result_cv = load_json_cv(path_json)

In [54]:
for chave in result_cv.keys():
  print(chave)

name
area
summary
skills
education
interview_questions

## Exibição do resultado

In [55]:
from IPython.display import display, Markdown

def show_cv_result(result: dict):
  md = f"### 📄 Análise e Resumo do Currículo\n"
  if "name" in result:
    md += f"- **Nome:** {result['name']}\n"
  if "area" in result:
    md += f"- **Área de Atuação:** {result['area']}\n"
  if "skills" in result:
    md += f"- **Competências:** {', '.join(result['skills'])}\n"
  if "summary" in result:
    md += f"- **Resumo do Perfil:** {result['summary']}\n"
  if "interview_questions" in result:
    md += f"- **Pergunta sugerida:** {result['interview_questions']}\n"
  display(Markdown(md))

In [56]:
show_cv_result(result_cv)

### 📄 Análise e Resumo do Currículo
- **Nome:** Alex Costa
- **Área de Atuação:** UI/UX Design e Front-end Development (Design de Produto, Interfaces e Marketing Digital)
- **Competências:** Figma, Design Systems, Adobe XD, Photoshop, Illustrator, Prototipagem interativa, HTML/CSS, JavaScript (ES6+), React.js, Vue.js, SASS, Storybook, Node.js (Express), Firebase (Firestore, Auth), Google Analytics, Hotjar, SEO, WordPress, Shopify, Mailchimp, Git, Webpack, Jira, Zeplin, A/B Testing, Branding, Mobile-first, Acessibilidade
- **Resumo do Perfil:** Profissional multidisciplinar com ~5 anos de experiência integrando design de interfaces, desenvolvimento front-end e estratégias de marketing digital. Experiência em criação e implementação de design systems (Figma + React), desenvolvimento de componentes reutilizáveis (Storybook), construção de landing pages de alta conversão e automação/otimização de UX com métricas mensuráveis.
- **Pergunta sugerida:** Pode descrever em detalhes o design system que você criou (estrutura de tokens, biblioteca de componentes, integração com Storybook e fluxo de manutenção)? Como foi o processo de adoção pelos >20 times e que métricas ou práticas específicas levaram à redução de 40% no tempo de desenvolvimento?

## Criando a vaga e descrição

In [57]:
job = {}

job['title'] = "Desenvolvedor(a) Full Stack"
job['description'] = "Estamos em busca de um(a) Desenvolvedor(a) Full Stack para integrar o time de tecnologia da nossa empresa, atuando em projetos estratégicos com foco em soluções escaláveis e orientadas a dados. O(a) profissional será responsável por desenvolver, manter e evoluir aplicações web robustas, além de colaborar com times multidisciplinares para entregar valor contínuo ao negócio."
job['details'] = """
Atividades:
- Desenvolver e manter aplicações web em ambientes modernos, utilizando tecnologias back-end e front-end.
- Trabalhar com equipes de produto, UX e dados para entender demandas e propor soluções.
- Criar APIs, integrações e dashboards interativos.
- Garantir boas práticas de versionamento, testes e documentação.
- Participar de revisões de código, deploys e melhorias contínuas na arquitetura das aplicações.

Pré-requisitos:
- Sólidos conhecimentos em Python, JavaScript e SQL.
- Experiência prática com frameworks como React, Node.js e Django.
- Familiaridade com versionamento de código usando Git.
- Experiência com serviços de nuvem, como AWS e Google Cloud Platform.
- Capacidade de trabalhar em equipe, com boa comunicação e perfil colaborativo.

Diferenciais:
- Conhecimento em Power BI ou outras ferramentas de visualização de dados.
- Experiência anterior em ambientes ágeis (Scrum, Kanban).
- Projetos próprios, contribuições open source ou portfólio técnico disponível.
- Certificações em nuvem ou áreas relacionadas à engenharia de software.
"""

### Salvando dados em um CSV

In [58]:
import csv
import os
import pandas as pd

path_job_csv = "vagas.csv"

def save_job_to_csv(data, filename):
  headers = ['title', 'description', 'details']
  file_exists = os.path.exists(filename)

  with open(filename, 'a', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames = headers, delimiter=';')
    if not file_exists:
      writer.writeheader()
    writer.writerow(data)

In [59]:
save_job_to_csv(job, path_job_csv)

In [60]:
df = pd.read_csv(path_job_csv, sep = ";")
display(df)

,title,description,details
0,Desenvolvedor(a) Full Stack,Estamos em busca de um(a) Desenvolvedor(a) Ful...,\nAtividades:\n- Desenvolver e manter aplicaçõ...

In [61]:
def load_job(csv_path):
  try:
    df = pd.read_csv(csv_path, sep = ";", encoding='utf-8')
    job = df.iloc[-1]
    prompt_text = f"""
    **Vaga para {job['title']}**

    **Descrição da Vaga:**
    {job['description']}

    **Detalhes Completos:**
    {job['details']}
    """

    return prompt_text.strip()
  except FileNotFoundError:
    return "Erro: Arquivo de vagas não encontrado"

In [62]:
job_details = load_job(path_job_csv)
print(job_details)

**Vaga para Desenvolvedor(a) Full Stack**

    **Descrição da Vaga:**
    Estamos em busca de um(a) Desenvolvedor(a) Full Stack para integrar o time de tecnologia da nossa empresa, atuando em projetos estratégicos com foco em soluções escaláveis e orientadas a dados. O(a) profissional será responsável por desenvolver, manter e evoluir aplicações web robustas, além de colaborar com times multidisciplinares para entregar valor contínuo ao negócio.

    **Detalhes Completos:**

Atividades:
- Desenvolver e manter aplicações web em ambientes modernos, utilizando tecnologias back-end e front-end.
- Trabalhar com equipes de produto, UX e dados para entender demandas e propor soluções.
- Criar APIs, integrações e dashboards interativos.
- Garantir boas práticas de versionamento, testes e documentação.
- Participar de revisões de código, deploys e melhorias contínuas na arquitetura das aplicações.

Pré-requisitos:
- Sólidos conhecimentos em Python, JavaScript e SQL.
- Experiência prática com frameworks como React, Node.js e Django.
- Familiaridade com versionamento de código usando Git.
- Experiência com serviços de nuvem, como AWS e Google Cloud Platform.
- Capacidade de trabalhar em equipe, com boa comunicação e perfil colaborativo.

Diferenciais:
- Conhecimento em Power BI ou outras ferramentas de visualização de dados.
- Experiência anterior em ambientes ágeis (Scrum, Kanban).
- Projetos próprios, contribuições open source ou portfólio técnico disponível.
- Certificações em nuvem ou áreas relacionadas à engenharia de software.

### Modificando o prompt e chain

In [63]:
prompt_template = ChatPromptTemplate.from_template("""
Você é um especialista em Recursos Humanos com vasta experiência em análise de currículos.
Sua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.
Importante: Responda apenas com o JSON estruturado e utilize somente essas chaves.
Cuide para que os nomes das chaves sejam exatamente esses.
Não adicione explicações ou anotações fora do JSON.
Schema desejado:
{schema}

---

Currículo a ser analisado:
'{cv}'

---

Vaga que o candidato está se candidatando:
'{job}'

""")
prompt_template

ChatPromptTemplate(input_variables=['cv', 'job', 'schema'], input_types={}, partial_variables={}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['cv', 'job', 'schema'], input_types={}, partial_variables={}, template="\nVocê é um especialista em Recursos Humanos com vasta experiência em análise de currículos.\nSua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.\nImportante: Responda apenas com o JSON estruturado e utilize somente essas chaves.\nCuide para que os nomes das chaves sejam exatamente esses.\nNão adicione explicações ou anotações fora do JSON.\nSchema desejado:\n{schema}\n\n---\n\nCurrículo a ser analisado:\n'{cv}'\n\n---\n\nVaga que o candidato está se candidatando:\n'{job}'\n\n"), additional_kwargs={})])

In [64]:
def process_cv(schema, content, job_details, prompt_template, llm):
  chain = prompt_template | llm
  output = chain.invoke({"schema": schema, "cv": content, "job": job_details})

  res = format_res(output.content)

  return output, res

In [65]:
output, res = process_cv(schema, content, job_details, prompt_template, llm)

In [66]:
output

AIMessage(content='{\n  "name": "Alex Costa",\n  "area": "Design de Interfaces e Desenvolvimento Front-end (UI/UX + Front-end)",\n  "summary": "Profissional multidisciplinar com ~5 anos de experiência integrando design, desenvolvimento front-end e marketing digital. Forte atuação em criação de interfaces (Figma), implementação com React.js e Vue.js, construção de design systems e componentes reutilizáveis (Storybook), além de experiência em otimização de conversões e integrações com ferramentas de análise.",\n  "skills": [\n    "Figma",\n    "Design Systems",\n    "Adobe XD",\n    "Photoshop",\n    "Illustrator",\n    "Prototipagem interativa",\n    "HTML/CSS (mobile-first, responsivo)",\n    "JavaScript (ES6+)",\n    "React.js",\n    "Vue.js",\n    "SASS",\n    "Storybook",\n    "Node.js (Express)",\n    "Firebase (Firestore, Auth)",\n    "PHP (plugins WordPress)",\n    "WordPress",\n    "Shopify",\n    "SEO",\n    "Google Analytics",\n    "A/B Testing",\n    "Git",\n    "Webpack",\n    "Jira",\n    "Zeplin",\n    "Mailchimp",\n    "Acessibilidade web"\n  ],\n  "education": "Bacharelado em Design Digital — Universidade Federal do Paraná (UFPR), Mar 2016 - Dez 2020. TCC: \'Design Systems para Aplicações Escaláveis: Unindo Figma e React\'. Curso Técnico em Marketing Digital — Instituto de Tecnologia e Design (ITEDE), Jan 2014 - Dez 2015.",\n  "interview_questions": "Seu histórico destaca sólido front-end (React/Vue) e backend leve com Node.js/Firebase, mas a vaga pede Python/Django, SQL e experiência com AWS/GCP. Pode detalhar sua experiência com desenvolvimento backend (incluindo bancos de dados relacionais/SQL), uso de Python/Django (se houver) e serviços em nuvem? Quais projetos concretos demonstram essa experiência e qual sua disponibilidade para migrar/aprender essas tecnologias?"\n}', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 1283, 'prompt_tokens': 1342, 'total_tokens': 2625, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 832, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': None, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5-mini-2025-08-07', 'system_fingerprint': None, 'id': 'chatcmpl-E3oduDxv1rtyW9OgLt5MR2MLE3dI7', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019f8128-c9e6-7972-8bc6-48e341401514-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1342, 'output_tokens': 1283, 'total_tokens': 2625, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 832}})

In [67]:
res

'{\n  "name": "Alex Costa",\n  "area": "Design de Interfaces e Desenvolvimento Front-end (UI/UX + Front-end)",\n  "summary": "Profissional multidisciplinar com ~5 anos de experiência integrando design, desenvolvimento front-end e marketing digital. Forte atuação em criação de interfaces (Figma), implementação com React.js e Vue.js, construção de design systems e componentes reutilizáveis (Storybook), além de experiência em otimização de conversões e integrações com ferramentas de análise.",\n  "skills": [\n    "Figma",\n    "Design Systems",\n    "Adobe XD",\n    "Photoshop",\n    "Illustrator",\n    "Prototipagem interativa",\n    "HTML/CSS (mobile-first, responsivo)",\n    "JavaScript (ES6+)",\n    "React.js",\n    "Vue.js",\n    "SASS",\n    "Storybook",\n    "Node.js (Express)",\n    "Firebase (Firestore, Auth)",\n    "PHP (plugins WordPress)",\n    "WordPress",\n    "Shopify",\n    "SEO",\n    "Google Analytics",\n    "A/B Testing",\n    "Git",\n    "Webpack",\n    "Jira",\n    "Zeplin",\n    "Mailchimp",\n    "Acessibilidade web"\n  ],\n  "education": "Bacharelado em Design Digital — Universidade Federal do Paraná (UFPR), Mar 2016 - Dez 2020. TCC: \'Design Systems para Aplicações Escaláveis: Unindo Figma e React\'. Curso Técnico em Marketing Digital — Instituto de Tecnologia e Design (ITEDE), Jan 2014 - Dez 2015.",\n  "interview_questions": "Seu histórico destaca sólido front-end (React/Vue) e backend leve com Node.js/Firebase, mas a vaga pede Python/Django, SQL e experiência com AWS/GCP. Pode detalhar sua experiência com desenvolvimento backend (incluindo bancos de dados relacionais/SQL), uso de Python/Django (se houver) e serviços em nuvem? Quais projetos concretos demonstram essa experiência e qual sua disponibilidade para migrar/aprender essas tecnologias?"\n}'

In [68]:
structured_data = parse_res_llm(res, fields)
save_json_cv(structured_data, path_json)
result_cv = load_json_cv("curriculos.json")
show_cv_result(result_cv)

### 📄 Análise e Resumo do Currículo
- **Nome:** Alex Costa
- **Área de Atuação:** Design de Interfaces e Desenvolvimento Front-end (UI/UX + Front-end)
- **Competências:** Figma, Design Systems, Adobe XD, Photoshop, Illustrator, Prototipagem interativa, HTML/CSS (mobile-first, responsivo), JavaScript (ES6+), React.js, Vue.js, SASS, Storybook, Node.js (Express), Firebase (Firestore, Auth), PHP (plugins WordPress), WordPress, Shopify, SEO, Google Analytics, A/B Testing, Git, Webpack, Jira, Zeplin, Mailchimp, Acessibilidade web
- **Resumo do Perfil:** Profissional multidisciplinar com ~5 anos de experiência integrando design, desenvolvimento front-end e marketing digital. Forte atuação em criação de interfaces (Figma), implementação com React.js e Vue.js, construção de design systems e componentes reutilizáveis (Storybook), além de experiência em otimização de conversões e integrações com ferramentas de análise.
- **Pergunta sugerida:** Seu histórico destaca sólido front-end (React/Vue) e backend leve com Node.js/Firebase, mas a vaga pede Python/Django, SQL e experiência com AWS/GCP. Pode detalhar sua experiência com desenvolvimento backend (incluindo bancos de dados relacionais/SQL), uso de Python/Django (se houver) e serviços em nuvem? Quais projetos concretos demonstram essa experiência e qual sua disponibilidade para migrar/aprender essas tecnologias?

## Análise detalhada

In [69]:
schema = """
{
  "name": "Nome completo do candidato",
  "area": "Área ou setor principal onde o candidato atua. Classifique em apenas uma: Desenvolvimento, Marketing, Vendas, Financeiro, Administrativo, Outros",
  "summary": "Resumo objetivo sobre o perfil profissional do candidato",
  "skills": ["competência 1", "competência 2", "..."],
  "education": "Resumo da formação acadêmica mais relevante",
  "interview_questions": ["Pelo menos 3 perguntas úteis para entrevista com base no currículo, para esclarecer algum ponto ou explorar melhor"],
  "strengths": ["Pontos fortes e aspectos que indicam alinhamento com o perfil ou vaga desejada"],
  "areas_for_development": ["Pontos que indicam possíveis lacunas, fragilidades ou necessidades de desenvolvimento"],
  "important_considerations": ["Observações específicas que merecem verificação ou cuidado adicional"],
  "final_recommendations": "Resumo avaliativo final com sugestões de próximos passos (ex: seguir com entrevista, indicar para outra vaga)"
}
"""

In [70]:
fields = [
    "name",
    "area",
    "summary",
    "skills",
    "education",
    "interview_questions",
    "strengths",
    "areas_for_development",
    "important_considerations",
    "final_recommendations"
]

In [71]:
output, res = process_cv(schema, content, job_details, prompt_template, llm)

In [72]:
structured_data = parse_res_llm(res, fields)

save_json_cv(structured_data, path_json)
result_cv = load_json_cv(path_json)
structured_data

{'name': 'Alex Costa',
 'area': 'Desenvolvimento',
 'summary': 'Profissional multidisciplinar com ~5 anos de experiência integrando design de interfaces, front-end development e marketing digital. Experiência prática com Figma, design systems e implementação front-end (React.js, Vue.js), criação de componentes reutilizáveis e otimização de conversão. Apresenta conhecimentos básicos em Node.js e Firebase e forte foco em usabilidade e performance.',
 'skills': ['Design de interfaces (Figma, Adobe XD, Photoshop, Illustrator)',
  'Design systems e component libraries (Storybook)',
  'Front-end: HTML/CSS, SASS, JavaScript (ES6+), React.js, Vue.js',
  'Prototipagem interativa e UX',
  'Desenvolvimento de componentes reutilizáveis',
  'Node.js (Express) para back-end leve',
  'Firebase (Firestore, Auth)',
  'SEO e otimização de conversão',
  'Integração e automação em CMS (WordPress, Shopify, Webflow)',
  'Analytics e ferramentas de comportamento (Google Analytics, Hotjar)',
  'Controle de versão e workflows (Git, Webpack, Jira)',
  'A/B Testing e otimização baseada em dados',
  'Inglês fluente (TOEIC 950)'],
 'education': 'Bacharelado em Design Digital (UFPR, 2016–2020) — TCC sobre Design Systems integrando Figma e React. Curso Técnico em Marketing Digital (ITEDE, 2014–2015).',
 'interview_questions': ['Pode detalhar projetos em que você foi responsável por APIs ou back-end mais complexos? Quais tecnologias e bancos de dados utilizou?',
  'Qual sua experiência com Python e frameworks como Django? Tem exemplos práticos ou projetos pessoais/produção?',
  'Descreva seu nível de familiaridade com SQL e modelagem de dados relacionais. Já trabalhou com consultas complexas ou otimização de queries?',
  'Tem experiência com serviços de nuvem (AWS, GCP) e ferramentas de deploy/CI-CD (Docker, GitHub Actions, Jenkins)?',
  'Como você aborda testes (unitários, integração) em aplicações front-end e back-end? Pode citar ferramentas e práticas que já utilizou?',
  'Você pode compartilhar portfólio técnico ou repositórios (GitHub) com exemplos de código, especialmente do design system e componentes em React/Vue?',
  'Em projetos anteriores, qual foi sua participação na definição de arquitetura e decisões de escalabilidade?'],
 'strengths': ['Combina habilidades de design e front-end, facilitando entrega de interfaces com foco em usabilidade e implementação',
  'Experiência prática com design systems e componentes reutilizáveis, favorecendo escalabilidade e consistência',
  'Histórico comprovado de impacto em métricas (ex.: aumento de engajamento e tráfego orgânico)',
  'Forte capacidade de colaboração com times de marketing e produto',
  'Portfólio diversificado (web, mobile, e-commerce) e certificações relevantes em UX e JavaScript'],
 'areas_for_development': ['Ausência de menção direta a Python/Django — requisito explícito da vaga',
  'Pouca ou nenhuma evidência de experiência com SQL e bancos relacionais em nível avançado',
  'Não há referência clara a experiência com AWS/GCP ou práticas de infraestrutura/CI-CD robustas',
  'Testes automatizados e boas práticas de backend (arquitetura, escalabilidade) não estão detalhados',
  'Não há indicação de uso de TypeScript (comum em stacks modernos que incluem React/Node)'],
 'important_considerations': ['Verificar experiência prática em back-end e com bancos de dados (SQL) antes de avançar para contratação como full stack',
  'Solicitar portfólio técnico e acesso a repositórios para avaliar qualidade de código e aderência a boas práticas',
  'Confirmar proficiência em cloud (AWS/GCP) e ferramentas de deploy/CI-CD ou plano de upskilling',
  'Checar pretensões salariais e disponibilidade para assumir responsabilidades de back-end mais profundas',
  'Aproveitar fluência em inglês para possíveis demandas de comunicação técnica e documentação'],
 'final_recommendations': 'Candidato com perfil forte em front-end, UX e design systems, adequado para posições híbridas front-end/UX ou para times que valorizem produto e conversão. Para vaga de Desenvolvedor Full Stack que exige Python/Django e SQL, recomenda-se avançar para uma etapa técnica: (1) entrevista técnica focada em back-end e bancos de dados; (2) teste prático em Python/SQL e um exercício de integração/API; (3) revisão de portfólio e código. Se os resultados forem insatisfatórios de back-end, considerar para vaga de Front-End Engineer / Product Designer ou planejar plano de transição/upskilling para back-end.'}

In [73]:
from IPython.display import display, Markdown

def show_cv_result(result: dict):
    md = f"### 📄 Análise e Resumo do Currículo\n"
    if "name" in result:
        md += f"- **Nome:** {result['name']}\n"
    if "area" in result:
        md += f"- **Área de Atuação:** {result['area']}\n"
    if "skills" in result:
        md += f"- **Competências:** {', '.join(result['skills'])}\n"
    if "summary" in result:
        md += f"- **Resumo do Perfil:** {result['summary']}\n"
    if "interview_questions" in result:
        md += f"- **Perguntas sugeridas:**\n"
        md += "\n".join([f"  - {q}" for q in result["interview_questions"]]) + "\n"
    if "strengths" in result:
        md += f"- **Pontos fortes (ou Alinhamentos):**\n"
        md += "\n".join([f"  - {s}" for s in result["strengths"]]) + "\n"
    if "areas_for_development" in result:
        md += f"- **Pontos a desenvolver (ou Desalinhamentos):**\n"
        md += "\n".join([f"  - {a}" for a in result["areas_for_development"]]) + "\n"
    if "important_considerations" in result:
        md += f"- **Pontos de atenção:**\n"
        md += "\n".join([f"  - {i}" for i in result["important_considerations"]]) + "\n"
    if "final_recommendations" in result:
        md += f"- **Conclusão e recomendações:** {result['final_recommendations']}\n"
    display(Markdown(md))

show_cv_result(result_cv)

### 📄 Análise e Resumo do Currículo
- **Nome:** Alex Costa
- **Área de Atuação:** Desenvolvimento
- **Competências:** Design de interfaces (Figma, Adobe XD, Photoshop, Illustrator), Design systems e component libraries (Storybook), Front-end: HTML/CSS, SASS, JavaScript (ES6+), React.js, Vue.js, Prototipagem interativa e UX, Desenvolvimento de componentes reutilizáveis, Node.js (Express) para back-end leve, Firebase (Firestore, Auth), SEO e otimização de conversão, Integração e automação em CMS (WordPress, Shopify, Webflow), Analytics e ferramentas de comportamento (Google Analytics, Hotjar), Controle de versão e workflows (Git, Webpack, Jira), A/B Testing e otimização baseada em dados, Inglês fluente (TOEIC 950)
- **Resumo do Perfil:** Profissional multidisciplinar com ~5 anos de experiência integrando design de interfaces, front-end development e marketing digital. Experiência prática com Figma, design systems e implementação front-end (React.js, Vue.js), criação de componentes reutilizáveis e otimização de conversão. Apresenta conhecimentos básicos em Node.js e Firebase e forte foco em usabilidade e performance.
- **Perguntas sugeridas:**
  - Pode detalhar projetos em que você foi responsável por APIs ou back-end mais complexos? Quais tecnologias e bancos de dados utilizou?
  - Qual sua experiência com Python e frameworks como Django? Tem exemplos práticos ou projetos pessoais/produção?
  - Descreva seu nível de familiaridade com SQL e modelagem de dados relacionais. Já trabalhou com consultas complexas ou otimização de queries?
  - Tem experiência com serviços de nuvem (AWS, GCP) e ferramentas de deploy/CI-CD (Docker, GitHub Actions, Jenkins)?
  - Como você aborda testes (unitários, integração) em aplicações front-end e back-end? Pode citar ferramentas e práticas que já utilizou?
  - Você pode compartilhar portfólio técnico ou repositórios (GitHub) com exemplos de código, especialmente do design system e componentes em React/Vue?
  - Em projetos anteriores, qual foi sua participação na definição de arquitetura e decisões de escalabilidade?
- **Pontos fortes (ou Alinhamentos):**
  - Combina habilidades de design e front-end, facilitando entrega de interfaces com foco em usabilidade e implementação
  - Experiência prática com design systems e componentes reutilizáveis, favorecendo escalabilidade e consistência
  - Histórico comprovado de impacto em métricas (ex.: aumento de engajamento e tráfego orgânico)
  - Forte capacidade de colaboração com times de marketing e produto
  - Portfólio diversificado (web, mobile, e-commerce) e certificações relevantes em UX e JavaScript
- **Pontos a desenvolver (ou Desalinhamentos):**
  - Ausência de menção direta a Python/Django — requisito explícito da vaga
  - Pouca ou nenhuma evidência de experiência com SQL e bancos relacionais em nível avançado
  - Não há referência clara a experiência com AWS/GCP ou práticas de infraestrutura/CI-CD robustas
  - Testes automatizados e boas práticas de backend (arquitetura, escalabilidade) não estão detalhados
  - Não há indicação de uso de TypeScript (comum em stacks modernos que incluem React/Node)
- **Pontos de atenção:**
  - Verificar experiência prática em back-end e com bancos de dados (SQL) antes de avançar para contratação como full stack
  - Solicitar portfólio técnico e acesso a repositórios para avaliar qualidade de código e aderência a boas práticas
  - Confirmar proficiência em cloud (AWS/GCP) e ferramentas de deploy/CI-CD ou plano de upskilling
  - Checar pretensões salariais e disponibilidade para assumir responsabilidades de back-end mais profundas
  - Aproveitar fluência em inglês para possíveis demandas de comunicação técnica e documentação
- **Conclusão e recomendações:** Candidato com perfil forte em front-end, UX e design systems, adequado para posições híbridas front-end/UX ou para times que valorizem produto e conversão. Para vaga de Desenvolvedor Full Stack que exige Python/Django e SQL, recomenda-se avançar para uma etapa técnica: (1) entrevista técnica focada em back-end e bancos de dados; (2) teste prático em Python/SQL e um exercício de integração/API; (3) revisão de portfólio e código. Se os resultados forem insatisfatórios de back-end, considerar para vaga de Front-End Engineer / Product Designer ou planejar plano de transição/upskilling para back-end.

## Calculando um score

In [74]:
prompt_score = """
Com base na vaga específica, calcule a pontuação final (de 0.0 a 10.0).
O retorno para esse campo deve conter apenas a pontuação final (x.x) sem mais nenhum texto ou anotação.
Seja justo e rigoroso ao atribuir as notas. A nota 10.0 só deve ser atribuída para candidaturas que superem todas as expectativas da vaga.

Critérios de avaliação:
1. Experiência (Peso: 35% do total): Análise de posições anteriores, tempo de atuação e similaridade com as responsabilidades da vaga.
2. Habilidades Técnicas (Peso: 25% do total): Verifique o alinhamento das habilidades técnicas com os requisitos mencionados na vaga.
3. Educação (Peso: 15% do total): Avalie a relevância da graduação/certificações para o cargo, incluindo instituições e anos de estudo.
4. Pontos Fortes (Peso: 15% do total): Avalie a relevância dos pontos fortes (ou alinhamentos) para a vaga.
5. Pontos Fracos (Desconto de até 10%): Avalie a gravidade dos pontos fracos (ou desalinhamentos) para a vaga.
"""

In [75]:
prompt_template = ChatPromptTemplate.from_template("""
Você é um especialista em Recursos Humanos com vasta experiência em análise de currículos.
Sua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.
Responda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses.
Não adicione explicações ou anotações fora do JSON.
Schema desejado:
{schema}

---
Para o cálculo do campo score:
{prompt_score}

---

Currículo a ser analisado:
'{cv}'

---

Vaga que o candidato está se candidatando:
'{job}'

""")
prompt_template

ChatPromptTemplate(input_variables=['cv', 'job', 'prompt_score', 'schema'], input_types={}, partial_variables={}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['cv', 'job', 'prompt_score', 'schema'], input_types={}, partial_variables={}, template="\nVocê é um especialista em Recursos Humanos com vasta experiência em análise de currículos.\nSua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.\nResponda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses.\nNão adicione explicações ou anotações fora do JSON.\nSchema desejado:\n{schema}\n\n---\nPara o cálculo do campo score:\n{prompt_score}\n\n---\n\nCurrículo a ser analisado:\n'{cv}'\n\n---\n\nVaga que o candidato está se candidatando:\n'{job}'\n\n"), additional_kwargs={})])

In [76]:
schema = """
{
  "name": "Nome completo do candidato",
  "area": "Área ou setor principal onde o candidato atua. Classifique em apenas uma: Desenvolvimento, Marketing, Vendas, Financeiro, Administrativo, Outros",
  "summary": "Resumo objetivo sobre o perfil profissional do candidato",
  "skills": ["competência 1", "competência 2", "..."],
  "education": "Resumo da formação acadêmica mais relevante",
  "interview_questions": ["Pelo menos 3 perguntas úteis para entrevista com base no currículo, para esclarecer algum ponto ou explorar melhor"],
  "strengths": ["Pontos fortes e aspectos que indicam alinhamento com o perfil ou vaga desejada"],
  "areas_for_development": ["Pontos que indicam possíveis lacunas, fragilidades ou necessidades de desenvolvimento"],
  "important_considerations": ["Observações específicas que merecem verificação ou cuidado adicional"],
  "final_recommendations": "Resumo avaliativo final com sugestões de próximos passos (ex: seguir com entrevista, indicar para outra vaga)",
  "score": 0.0
}
"""

fields = [
    "name",
    "area",
    "summary",
    "skills",
    "education",
    "interview_questions",
    "strengths",
    "areas_for_development",
    "important_considerations",
    "final_recommendations",
    "score"
]

## Conclusão e Funções finais

    Parâmetros:
    - schema: estrutura de dados esperada no resultado
    - job_details: informações da vaga
    - prompt_template: template do prompt LangChain
    - prompt_score: instrução adicional que influencia a avaliação do CV
    - llm: instância do modelo de linguagem (LangChain)

    Retorna:
    - output: resposta bruta do LLM
    - res: resposta formatada com base no schema

In [77]:
def parse_doc(file_path):
  from docling.document_converter import DocumentConverter

  converter = DocumentConverter()
  result = converter.convert(file_path)
  content = result.document.export_to_markdown()
  return content

In [78]:
def process_cv(schema, job_details, prompt_template, prompt_score, llm, file_path):
  if file_path:
    if not os.path.exists(file_path):
      raise FileNotFoundError(f"Arquivo não encontrado: {file_path}")

  content = parse_doc(file_path)

  chain = prompt_template | llm
  output = chain.invoke({"schema": schema, "cv": content, "job": job_details, "prompt_score": prompt_score})

  res = format_res(output.content)

  return output, res

In [79]:
file_cv = "/content/Currículo1.pdf"
output, res = process_cv(schema, job_details, prompt_template, prompt_score, llm, file_cv)
structured_data = parse_res_llm(res, fields)
structured_data

[INFO] 2026-07-20 20:19:38,892 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 20:19:38,894 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 20:19:38,948 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 20:19:38,949 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 20:19:39,228 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 20:19:39,229 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 20:19:39,236 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 20:19:39,237 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 20:19:39,351 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 20:19:39,353 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 20:19:39,458 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-07-20 20:19:39,460 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

{'name': 'Thomas A. Anderson',
 'area': 'Desenvolvimento',
 'summary': 'Desenvolvedor Full Stack com ~5 anos de experiência em desenvolvimento de software e análise de dados. Experiência prática com Python, JavaScript, SQL, React, Node.js e Django; atuação em projetos cloud (AWS/GCP), criação de APIs, dashboards e automação de relatórios. Possui formação em Ciência da Computação pela USP e certificações relevantes (AWS, Scrum, Google Data Analytics).',
 'skills': ['Python',
  'JavaScript',
  'SQL',
  'React',
  'Node.js',
  'Django',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Git',
  'Docker',
  'AWS (EC2, S3)',
  'Google Cloud Platform',
  'Pandas / NumPy',
  'Power BI / Tableau',
  'Testes automatizados',
  'Metodologias Ágeis (Scrum)'],
 'education': 'Bacharelado em Ciência da Computação - Universidade de São Paulo (USP), Fev 2018 - Dez 2022. TCC sobre otimização de algoritmos de ML; participação em grupo de pesquisa em IA.',
 'interview_questions': ['Pode detalhar sua responsabilidade direta nas APIs desenvolvidas na TechSolutions (escopo, endpoints críticos, volume de requisições, SLAs e integração com outros serviços)?',
  'Como você organiza o processo de deploy/CI-CD e infraestrutura na AWS/GCP em projetos onde atuou? Já utilizou ferramentas como Jenkins, GitHub Actions, Terraform ou CloudFormation?',
  'No projeto de recomendação para e-commerce: qual foi o pipeline completo (pré-processamento, modelo escolhido, validação, métricas usadas) e qual foi seu papel técnico no desenvolvimento e deploy desse modelo?',
  'Pode compartilhar links para repositórios, portfólio ou demos das aplicações full-stack mencionadas (Plataforma de Gestão de Projetos, projetos freelance)?',
  'Como você testa e garante a qualidade do front-end (React) em produção? Você já participou ativamente de code reviews e definição de boas práticas na equipe?'],
 'strengths': ['Alinhamento técnico forte com a vaga: Python, JavaScript, SQL, React, Node.js e Django presentes no currículo.',
  'Formação relevante (USP) e certificações pertinentes (AWS Certified Developer, Scrum, Google Data Analytics).',
  'Experiência prática com cloud (AWS/GCP) e desenvolvimento de APIs, além de habilidade em criação de dashboards e análise de dados.',
  'Experiência híbrida (freelance, estágio e posição efetiva) que demonstra autonomia e contato com requisitos de negócio.',
  'Conhecimento em testes automatizados e trabalho em equipes ágeis.'],
 'areas_for_development': ['Nível atual indicado como Júnior — pode faltar experiência em arquitetura de sistemas de grande escala e liderança técnica para vagas sênior.',
  'Pouca menção explícita a práticas de CI/CD, infraestrutura como código (Terraform/CloudFormation) e monitoramento/observabilidade.',
  'Detalhes sobre deploys em produção, escalabilidade e gerenciamento de incidentes não estão claros.',
  'Experiência front-end mais descritiva que quantitativa — falta informação sobre testes de UI, performance e acessibilidade.'],
 'important_considerations': ['Verificar evidências dos resultados citados (redução de bugs 30%, aumento de conversões 18%) para entender a contribuição individual e métricas base.',
  'Confirmar validade e escopo da certificação AWS (nível e data) e se há experiência prática com serviços além de EC2/S3.',
  'Solicitar acesso a GitHub/portfólio para avaliar qualidade de código, padrões adotados e maturidade técnica.',
  'Esclarecer nível de autonomia e responsabilidades na TechSolutions (ownership de features, revisão de arquitetura, coordenação com times de produto/UX).',
  'Validar disponibilidade, pretensão salarial e interesse em assumir responsabilidades adicionais (devops, arquitetura, mentoring) caso a vaga exija.'],
 'final_recommendations': 'Candidato bem alinhado tecnicamente com a vaga Full Stack; recomenda-se avançar para uma entrevista técnica com foco em avaliação prática (coding challenge ou revisão de código) e perguntas sobre deploy/CI-CD, escalabilidade e contribuição em projetos citados. Solicitar portfólio/GitHub e confirmar detalhes das métricas e certificações antes de decisão final. Se a vaga exigir nível sênior/arquitetura, considerar para vaga júnior/pleno; caso contrário, seguir com processo.',
 'score': 7.1}

## Salvando no JSON

In [80]:
def save_json_cv(new_data, path_json, key_name="name"):
  if os.path.exists(path_json):
    with open(path_json, "r", encoding="utf-8") as f:
      data = json.load(f)
  else:
    data = []

  if isinstance(data, dict):
    data = [data]

  candidates = [entry.get(key_name) for entry in data]
  if new_data.get(key_name) in candidates:
    print(f"Currículo '{new_data.get(key_name)}' já registrado. Ignorando")
    return

  data.append(new_data)
  with open(path_json, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

In [81]:
save_json_cv(structured_data, path_json)

In [82]:
def display_json_table(path_json):
  with open(path_json, "r", encoding="utf-8") as f:
    data = json.load(f)

  df = pd.json_normalize(data)
  return df

In [83]:
df = display_json_table(path_json)
display(df)

,name,area,summary,skills,education,interview_questions,strengths,areas_for_development,important_considerations,final_recommendations,score
0,Alex Costa,Desenvolvimento,Profissional multidisciplinar com ~5 anos de e...,"[Design de interfaces (Figma, Adobe XD, Photos...","Bacharelado em Design Digital (UFPR, 2016–2020...",[Pode detalhar projetos em que você foi respon...,"[Combina habilidades de design e front-end, fa...",[Ausência de menção direta a Python/Django — r...,[Verificar experiência prática em back-end e c...,"Candidato com perfil forte em front-end, UX e ...",NaN
1,Thomas A. Anderson,Desenvolvimento,Desenvolvedor Full Stack com ~5 anos de experi...,"[Python, JavaScript, SQL, React, Node.js, Djan...",Bacharelado em Ciência da Computação - Univers...,[Pode detalhar sua responsabilidade direta nas...,"[Alinhamento técnico forte com a vaga: Python,...",[Nível atual indicado como Júnior — pode falta...,[Verificar evidências dos resultados citados (...,Candidato bem alinhado tecnicamente com a vaga...,7.1

In [84]:
path = "/content/Currículo3.pdf"
#path = "Currículo3.pdf"
output, res = process_cv(schema, job_details, prompt_template, prompt_score, llm, path)
structured_data = parse_res_llm(res, fields)
save_json_cv(structured_data, path_json)

df = display_json_table(path_json)
display(df)

[INFO] 2026-07-20 20:20:43,371 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 20:20:43,374 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 20:20:43,469 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 20:20:43,470 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-07-20 20:20:43,876 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 20:20:43,878 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 20:20:43,883 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 20:20:43,885 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-07-20 20:20:44,062 [RapidOCR] base.py:23: Using engine_name: torch
[INFO] 2026-07-20 20:20:44,063 [RapidOCR] device_config.py:57: Using CPU device
[INFO] 2026-07-20 20:20:44,208 [RapidOCR] download_file.py:60: File exists and is valid: /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-07-20 20:20:44,210 [RapidOCR] main.py:50: Using /usr/local/lib/python3.12/dist-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

Currículo 'Alex Costa' já registrado. Ignorando

,name,area,summary,skills,education,interview_questions,strengths,areas_for_development,important_considerations,final_recommendations,score
0,Alex Costa,Desenvolvimento,Profissional multidisciplinar com ~5 anos de e...,"[Design de interfaces (Figma, Adobe XD, Photos...","Bacharelado em Design Digital (UFPR, 2016–2020...",[Pode detalhar projetos em que você foi respon...,"[Combina habilidades de design e front-end, fa...",[Ausência de menção direta a Python/Django — r...,[Verificar experiência prática em back-end e c...,"Candidato com perfil forte em front-end, UX e ...",NaN
1,Thomas A. Anderson,Desenvolvimento,Desenvolvedor Full Stack com ~5 anos de experi...,"[Python, JavaScript, SQL, React, Node.js, Djan...",Bacharelado em Ciência da Computação - Univers...,[Pode detalhar sua responsabilidade direta nas...,"[Alinhamento técnico forte com a vaga: Python,...",[Nível atual indicado como Júnior — pode falta...,[Verificar evidências dos resultados citados (...,Candidato bem alinhado tecnicamente com a vaga...,7.1

In [85]:
df[["name", "score", "summary"]]

,name,score,summary
0,Alex Costa,NaN,Profissional multidisciplinar com ~5 anos de e...
1,Thomas A. Anderson,7.1,Desenvolvedor Full Stack com ~5 anos de experi...


## Interface com Streamlit

In [86]:
!pip install -q streamlit python-dotenv
!npm install -q localtunnel

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 31.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 54.8 MB/s eta 0:00:00
⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼
added 22 packages in 3s
⠼
⠼3 packages are looking for funding
⠼  run `npm fund` for details
⠼

In [ ]:
%%writefile .env
GROQ_API_KEY=#######

Writing .env

In [ ]:
%%writefile utils_proj03.py
import os
from docling.document_converter import DocumentConverter
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate, MessagesPlaceholder
import json
import pandas as pd
import csv
import streamlit as st

def load_llm(id_model, temperature):
  llm = ChatGroq(
      model=id_model,
      temperature=temperature,
      max_tokens=None,
      timeout=None,
      max_retries=2,
  )
  return llm


def format_res(res, return_thinking=False):
  res = res.strip()

  if return_thinking:
    res = res.replace("<think>", "[pensando...] ")
    res = res.replace("</think>", "\n---\n")

  else:
    if "</think>" in res:
      res = res.split("</think>")[-1].strip()

  return res


def parse_doc(file_path):
  converter = DocumentConverter()
  result = converter.convert(file_path)
  content = result.document.export_to_markdown()
  return content


def parse_res_llm(response_text: str, required_fields: list) -> dict:
    try:
        # Remove a parte do raciocínio (<think>...</think>)
        if "</think>" in response_text:
            response_text = response_text.split("</think>")[-1].strip()

        # Localiza o JSON e faz o parsing
        start_idx = response_text.find('{')
        end_idx = response_text.rfind('}') + 1
        if start_idx == -1 or end_idx == 0:
            raise json.JSONDecodeError("Nenhum JSON encontrado na resposta", response_text, 0)

        json_str = response_text[start_idx:end_idx]
        info_cv = json.loads(json_str)

        for field in required_fields:
            if field not in info_cv:
                info_cv[field] = []

        return info_cv

    except json.JSONDecodeError:
        #Erro ao interpretar a resposta do modelo
        return


def save_json_cv(new_data, path_json, key_name="name"):
    # Carrega o JSON existente, se houver
    if os.path.exists(path_json):
        with open(path_json, "r", encoding="utf-8") as f:
            data = json.load(f)
    else:
        data = []

    if isinstance(data, dict):
        data = [data]

    # Verifica se já existe um currículo com o mesmo nome
    candidates = [entry.get(key_name) for entry in data]
    if new_data.get(key_name) in candidates:
        st.warning(f"Currículo '{new_data.get(key_name)}' já registrado. Ignorando.")
        return

    # Adiciona e salva
    data.append(new_data)
    with open(path_json, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def load_json_cv(path_json):
    with open(path_json, "r", encoding="utf-8") as f:
        return json.load(f)


def show_cv_result(result: dict):
    md = f"### 📄 Análise e Resumo do Currículo\n"
    if "name" in result:
        md += f"- **Nome:** {result['name']}\n"
    if "area" in result:
        md += f"- **Área de Atuação:** {result['area']}\n"
    if "skills" in result:
        md += f"- **Competências:** {', '.join(result['skills'])}\n"
    if "summary" in result:
        md += f"- **Resumo do Perfil:** {result['summary']}\n"
    if "interview_questions" in result:
        md += f"- **Perguntas sugeridas:**\n"
        md += "\n".join([f"  - {q}" for q in result["interview_questions"]]) + "\n"
    if "strengths" in result:
        md += f"- **Pontos fortes (ou Alinhamentos):**\n"
        md += "\n".join([f"  - {s}" for s in result["strengths"]]) + "\n"
    if "areas_for_development" in result:
        md += f"- **Pontos a desenvolver (ou Desalinhamentos):**\n"
        md += "\n".join([f"  - {a}" for a in result["areas_for_development"]]) + "\n"
    if "important_considerations" in result:
        md += f"- **Pontos de atenção:**\n"
        md += "\n".join([f"  - {i}" for i in result["important_considerations"]]) + "\n"
    if "final_recommendations" in result:
        md += f"- **Conclusão e recomendações:** {result['final_recommendations']}\n"
    return md


def save_job_to_csv(data, filename):
    headers = ['title', 'description', 'details']
    file_exists = os.path.exists(filename)

    with open(filename, 'a', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=headers, delimiter=';')
        if not file_exists:
            writer.writeheader()
        writer.writerow(data)


def load_job(csv_path):
  try:
    df = pd.read_csv(csv_path, sep=';', encoding='utf-8')
    job = df.iloc[-1]
    prompt_text = f"""
    **Vaga para {job['title']}**

    **Descrição da Vaga:**
    {job['description']}

    **Detalhes Completos:**
    {job['details']}
    """

    return prompt_text.strip()

  except FileNotFoundError:
    return "Erro: Arquivo de vagas não encontrado"

def process_cv(schema, job_details, prompt_template, prompt_score, llm, file_path):

  if file_path:
    if not os.path.exists(file_path):
      raise FileNotFoundError(f"Arquivo não encontrado: {file_path}")

  content = parse_doc(file_path)

  chain = prompt_template | llm
  output = chain.invoke({"schema": schema, "cv": content, "job": job_details, "prompt_score": prompt_score})

  res = format_res(output.content)

  return output, res


def display_json_table(path_json):
  with open(path_json, "r", encoding="utf-8") as f:
    data = json.load(f)

  df = pd.DataFrame(data)
  return df

Writing utils_proj03.py

In [ ]:
%%writefile app03.py
import streamlit as st
import uuid
from utils_proj03 import *
from dotenv import load_dotenv
load_dotenv()

st.set_page_config(page_title="Triagem e Análise de Currículos", page_icon="📄", layout="wide")

id_model = "deepseek-r1-distill-llama-70b"
temperature = 0.7
json_file = 'curriculos.json'
path_job_csv = "vagas.csv"

llm = load_llm(id_model, temperature)

job = {}
job['title'] = "Desenvolvedor(a) Full Stack"
job['description'] = "Estamos em busca de um(a) Desenvolvedor(a) Full Stack para integrar o time de tecnologia da nossa empresa, atuando em projetos estratégicos com foco em soluções escaláveis e orientadas a dados. O(a) profissional será responsável por desenvolver, manter e evoluir aplicações web robustas, além de colaborar com times multidisciplinares para entregar valor contínuo ao negócio."
job['details'] = """
Atividades:
- Desenvolver e manter aplicações web em ambientes modernos, utilizando tecnologias back-end e front-end.
- Trabalhar com equipes de produto, UX e dados para entender demandas e propor soluções.
- Criar APIs, integrações e dashboards interativos.
- Garantir boas práticas de versionamento, testes e documentação.
- Participar de revisões de código, deploys e melhorias contínuas na arquitetura das aplicações.

Pré-requisitos:
- Sólidos conhecimentos em Python, JavaScript e SQL.
- Experiência prática com frameworks como React, Node.js e Django.
- Familiaridade com versionamento de código usando Git.
- Experiência com serviços de nuvem, como AWS e Google Cloud Platform.
- Capacidade de trabalhar em equipe, com boa comunicação e perfil colaborativo.

Diferenciais:
- Conhecimento em Power BI ou outras ferramentas de visualização de dados.
- Experiência anterior em ambientes ágeis (Scrum, Kanban).
- Projetos próprios, contribuições open source ou portfólio técnico disponível.
- Certificações em nuvem ou áreas relacionadas à engenharia de software.
"""

schema = """
{
  "name": "Nome completo do candidato",
  "area": "Área ou setor principal que o candidato atua. Classifique em apenas uma: Desenvolvimento, Marketing, Vendas, Financeiro, Administrativo, Outros",
  "summary": "Resumo objetivo sobre o perfil profissional do candidato",
  "skills": ["competência 1", "competência 2", "..."],
  "education": "Resumo da formação acadêmica mais relevante",
  "interview_questions": ["Pelo menos 3 perguntas úteis para entrevista com base no currículo, para esclarecer algum ponto ou explorar melhor"],
  "strengths": ["Pontos fortes e aspectos que indicam alinhamento com o perfil ou vaga desejada"],
  "areas_for_development": ["Pontos que indicam possíveis lacunas, fragilidades ou necessidades de desenvolvimento"],
  "important_considerations": ["Observações específicas que merecem verificação ou cuidado adicional"],
  "final_recommendations": "Resumo avaliativo final com sugestões de próximos passos (ex: seguir com entrevista, indicar para outra vaga)",
  "score": 0.0
}
"""

fields = [
    "name",
    "area",
    "summary",
    "skills",
    "education",
    "interview_questions",
    "strengths",
    "areas_for_development",
    "important_considerations",
    "final_recommendations",
    "score"
]

prompt_score = """
Com base na vaga específica, calcule a pontuação final (de 0.0 a 10.0).
O retorno para esse campo deve conter apenas a pontuação final (x.x) sem mais nenhum texto ou anotação.
Seja justo e rigoroso ao atribuir as notas. A nota 10.0 só deve ser atribuída para candidaturas que superem todas as expectativas da vaga.

Critérios de avaliação:
1. Experiência (Peso: 35% do total): Análise de posições anteriores, tempo de atuação e similaridade com as responsabilidades da vaga.
2. Habilidades Técnicas (Peso: 25% do total): Verifique o alinhamento das habilidades técnicas com os requisitos mencionados na vaga.
3. Educação (Peso: 15% do total): Avalie a relevância da graduação/certificações para o cargo, incluindo instituições e anos de estudo.
4. Pontos Fortes (Peso: 15% do total): Avalie a relevância dos pontos fortes (ou alinhamentos) para a vaga.
5. Pontos Fracos (Desconto de até 10%): Avalie a gravidade dos pontos fracos (ou desalinhamentos) para a vaga.
"""

prompt_template = ChatPromptTemplate.from_template("""
Você é um especialista em Recursos Humanos com vasta experiência em análise de currículos.
Sua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.
Responda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses.
Não adicione explicações ou anotações fora do JSON.
Schema desejado:
{schema}

---
Para o cálculo do campo score:
{prompt_score}

---

Currículo a ser analisado:
'{cv}'

---

Vaga que o candidato está se candidatando:
'{job}'

""")

if "uploader_key" not in st.session_state:
  st.session_state.uploader_key = str(uuid.uuid4())

if "selected_cv" not in st.session_state:
  st.session_state.selected_cv = None

# Salva descrição da vaga em um .csv
save_job_to_csv(job, path_job_csv)
job_details = load_job(path_job_csv)

col1, col2 = st.columns(2)
with col1:
  st.header("Triagem e Análise de Currículos")
  st.markdown("#### Vaga: {}".format(job["title"]))
with col2:
  uploaded_file = st.file_uploader("Envie um currículo em PDF", type=["pdf"], key=st.session_state.uploader_key)

if uploaded_file is not None:
  with st.spinner("Analisando o currículo..."):
    path = uploaded_file.name
    with open(path, "wb") as f:
      f.write(uploaded_file.read())

    output, res = process_cv(schema, job_details, prompt_template, prompt_score, llm, path)
    structured_data = parse_res_llm(res, fields)
    save_json_cv(structured_data, path_json=json_file, key_name="name")

    st.success("Currículo analisado com sucesso!")
    st.session_state.uploader_key = str(uuid.uuid4())

  st.write(show_cv_result(structured_data))

  with st.expander("Ver dados estruturados (JSON)"):
    st.json(structured_data)

if os.path.exists(json_file):
  st.subheader("Lista de currículos analisados", divider="gray")
  df = display_json_table(json_file)
  for i, row in df.iterrows():
    cols = st.columns([1, 3, 1, 5])
    with cols[0]:
      if st.button("Ver detalhes", key = f"btn_{i}"):
        st.session_state.selected_cv = row.to_dict()
    with cols[1]:
        st.write(f"**Nome:** {row.get('name', '-')}")
    with cols[2]:
        st.write(f"**Score:** {row.get('score', '-')}")
    with cols[3]:
        st.write(f"**Resumo:** {row.get('summary', '-')}")

if st.session_state.selected_cv:
  st.markdown("-----")
  st.write(show_cv_result(st.session_state.selected_cv))

  with st.expander("Ver dados estruturados (JSON)"):
    st.json(st.session_state.selected_cv)

if os.path.exists(json_file):
  with open(json_file, "r", encoding="utf-8") as f:
    json_data = f.read()
  st.download_button(
      label = "📥 Baixar arquivo .json",
      data = json_data,
      file_name = json_file,
      mime="application/json"
  )

  df = display_json_table(json_file)
  st.dataframe(df)

Writing app03.py

In [ ]:
!streamlit run app03.py &>/content/logs.txt &

!wget -q -O - ipv4.icanhazip.com
!npx localtunnel --port 8501

35.231.168.154
⠙your url is: https://fancy-mails-kick.loca.lt

> **Importante:** Caso o comando acima com localtunnel não funcione, use o código abaixo (Para mais detalhes, consulte a aula "Aviso sobre uso no Colab" da seção 2)

### Alternativa com ngrok

In [ ]:
!pip install pyngrok

In [ ]:
from pyngrok import ngrok

!ngrok config add-authtoken SEU_TOKEN_AQUI
!streamlit run app03.py --server.port 8501 &>/content/logs.txt &

public_url = ngrok.connect(8501)
public_url